# -*- coding: utf-8 -*-
"""
analyze_ablations.py
====================

Post-hoc analyses over a scored Besag-Clifford ensemble. Every analysis here
holds the ensemble fixed and varies only the scoring choice or the reporting,
so differences are attributable to the choice under study rather than to
ensemble variation.

Produces, from a re-scored ensemble CSV (see rescore_plans.py) :

  1. threshold  -- the opportunity-district count #{d : p_d^g >= tau} swept
                   over a grid of tau, with rank, exact lower-tail p-value,
                   number of distinct ensemble values, share of plans tied at
                   the mode, and correlation with the continuous functional.
                   Answers "the 0.6 cutoff is unjustified and untested".
  2. modes      -- O_g and its rank/p under the statewide, equal, and
                   district EI weighting modes. The district mode is the one
                   that propagates precinct-level posterior uncertainty, so
                   this is the experiment that shows whether uncertainty
                   propagation moves a conclusion.
  3. locality   -- how far the simulated plans travel: fraction of precincts
                   reassigned relative to the enacted plan and to the hub, and
                   the cut-edge / county-split distribution of the ensemble.
                   Makes the chain length k interpretable.
  4. ksweep     -- aggregates several completed runs (each a run-config JSON
                   plus its spoke CSV) into a single rank/p versus k table,
                   and doubles as the hub-replication table.

Each analysis writes a CSV, a LaTeX fragment, and (where useful) a figure.

Usage
-----
    python analyze_ablations.py threshold --scores outputs/bc_rescored_RUN.csv
    python analyze_ablations.py modes     --scores outputs/bc_rescored_RUN.csv
    python analyze_ablations.py locality  --scores outputs/bc_rescored_RUN.csv \
        --plans outputs/bc_plan_assignments_RUN.parquet
    python analyze_ablations.py ksweep --runs outputs/bc_run_config_*.json
"""

import argparse
import glob
import json
import os

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

MODE_LABELS = {'state': 'statewide-preference',
               'equal': 'unweighted',
               'dist': 'district-specific'}


# ----------------------------------------------------------------- helpers ---
def load_scores(path):
    """Load a re-scored ensemble and split it into (enacted row, spoke rows)."""
    df = pd.read_csv(path)
    if 'plan' not in df.columns and 'spoke' in df.columns:
        # A spoke CSV from a patched run: it has no enacted row, so the caller
        # must pass the re-scored file instead.
        raise SystemExit(
            "This looks like a spoke CSV, not a re-scored ensemble. Run "
            "rescore_plans.py first, or pass its output with --scores.")
    enacted = df[df['plan'] == 'enacted']
    if enacted.empty:
        raise SystemExit("No 'enacted' row found in the scores file.")
    spokes = df[~df['plan'].isin(['enacted', 'hub'])].reset_index(drop=True)
    return enacted.iloc[0], spokes


def rank_and_p(enacted_value, spoke_values):
    """Lower-tail Besag-Clifford rank and exact p-value.

    Matches the convention in the ensemble script: ties count toward the
    lower tail, which is the conservative direction for a claim that the
    enacted plan is unusually *low*. `p_mid` additionally reports the
    tie-corrected mid-rank p-value, which matters only for the discrete
    threshold statistic, where large ties are the whole point.
    """
    vals = np.asarray(pd.Series(spoke_values).dropna(), dtype=float)
    M = len(vals)
    n_le = int((vals <= enacted_value).sum())
    n_lt = int((vals < enacted_value).sum())
    p = (n_le + 1) / (M + 1)
    p_mid = (n_lt + 0.5 * (n_le - n_lt) + 1) / (M + 1)
    return {'rank': n_le + 1, 'M': M, 'p': p, 'p_mid': p_mid}


def parse_vectors(series):
    """Parse a column of JSON-encoded per-district probability vectors."""
    return np.array([json.loads(s) for s in series], dtype=float)


def write_latex(path, body, caption, label):
    with open(path, 'w') as fh:
        fh.write("% generated by analyze_ablations.py -- do not edit by hand\n")
        fh.write("\\begin{table}[t]\n\\centering\n")
        fh.write(f"\\caption{{{caption}}}\n\\label{{{label}}}\n")
        fh.write(body)
        fh.write("\n\\end{table}\n")
    print(f"  wrote {path}")


# --------------------------------------------------------------- threshold ---
def cmd_threshold(args):
    enacted, spokes = load_scores(args.scores)
    taus = [float(t) for t in args.taus.split(',')]
    rows = []
    for group, key in (('Latino', 'pL'), ('Black', 'pB')):
        col = f'{key}_{args.mode}'
        enacted_vec = np.array(json.loads(enacted[col]), dtype=float)
        spoke_mat = parse_vectors(spokes[col])
        o_col = f"{'O_L' if group == 'Latino' else 'O_B'}_{args.mode}"
        o_spokes = spokes[o_col].values
        o_enacted = float(enacted[o_col])

        cont = rank_and_p(o_enacted, o_spokes)
        rows.append({'group': group, 'statistic': 'expected count O_g',
                     'tau': None, 'enacted': o_enacted,
                     'distinct_values': len(np.unique(np.round(o_spokes, 9))),
                     'pct_tied_at_mode': 100.0 * pd.Series(o_spokes)
                     .round(9).value_counts(normalize=True).max(),
                     'corr_with_O': 1.0, **cont})

        for tau in taus:
            enacted_count = int((enacted_vec >= tau).sum())
            spoke_counts = (spoke_mat >= tau).sum(axis=1).astype(float)
            res = rank_and_p(enacted_count, spoke_counts)
            corr = (np.corrcoef(spoke_counts, o_spokes)[0, 1]
                    if spoke_counts.std() > 0 else float('nan'))
            rows.append({'group': group,
                         'statistic': f'threshold count (tau={tau:g})',
                         'tau': tau, 'enacted': enacted_count,
                         'distinct_values': len(np.unique(spoke_counts)),
                         'pct_tied_at_mode': 100.0 * pd.Series(spoke_counts)
                         .value_counts(normalize=True).max(),
                         'corr_with_O': corr, **res})

    out = pd.DataFrame(rows)
    csv_path = os.path.join(args.outdir, 'ablation_threshold_sweep.csv')
    out.to_csv(csv_path, index=False)
    print(f"  wrote {csv_path}")
    print(out.to_string(index=False))

    # LaTeX: one row per (group, tau), continuous functional first.
    lines = ["\\begin{tabular}{llrrrrr}", "\\toprule",
             "Group & Statistic & Enacted & Distinct & \\% tied & Rank & "
             "$p$ \\\\", "\\midrule"]
    for _, r in out.iterrows():
        lines.append(
            f"{r['group']} & {r['statistic']} & {r['enacted']:.4g} & "
            f"{int(r['distinct_values'])} & {r['pct_tied_at_mode']:.1f} & "
            f"{int(r['rank'])}/{int(r['M'])+1} & {r['p']:.4f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_latex(os.path.join(args.outdir, 'ablation_threshold_sweep.tex'),
                "\n".join(lines),
                "Threshold-count opportunity scoring swept over $\\tau$, "
                "compared with the continuous expected-count functional, over "
                "the same spoke ensemble.",
                "tab:threshold-sweep")

    # Figure: p-value versus tau, both groups, with the continuous result.
    fig, ax = plt.subplots(figsize=(5.2, 3.2))
    for group, marker in (('Latino', 'o'), ('Black', 's')):
        sub = out[(out['group'] == group) & out['tau'].notna()]
        ax.plot(sub['tau'], sub['p'], marker=marker, label=f'{group}: threshold count')
        cont = out[(out['group'] == group) & out['tau'].isna()].iloc[0]
        ax.axhline(cont['p'], linestyle='--', linewidth=1,
                   color='C0' if group == 'Latino' else 'C1')
    ax.axhline(0.05, color='grey', linestyle=':', linewidth=1)
    ax.set_xlabel(r'opportunity threshold $\tau$')
    ax.set_ylabel('exact lower-tail $p$')
    ax.set_yscale('log')
    ax.legend(fontsize=7)
    fig.tight_layout()
    for ext in ('pdf', 'png'):
        fig.savefig(os.path.join(args.outdir, f'ablation_threshold_sweep.{ext}'),
                    dpi=200)
    print(f"  wrote ablation_threshold_sweep.pdf/.png")


# ------------------------------------------------------------------- modes ---
def cmd_modes(args):
    enacted, spokes = load_scores(args.scores)
    rows = []
    for group, base in (('Latino', 'O_L'), ('Black', 'O_B')):
        for tag in ('state', 'equal', 'dist'):
            col = f'{base}_{tag}'
            if col not in spokes.columns or spokes[col].isna().all():
                continue
            res = rank_and_p(float(enacted[col]), spokes[col].values)
            rows.append({'group': group, 'mode': MODE_LABELS[tag],
                         'enacted': float(enacted[col]),
                         'spoke_mean': spokes[col].mean(),
                         'spoke_sd': spokes[col].std(),
                         'spoke_min': spokes[col].min(),
                         **res})
    out = pd.DataFrame(rows)
    csv_path = os.path.join(args.outdir, 'ablation_modes.csv')
    out.to_csv(csv_path, index=False)
    print(f"  wrote {csv_path}")
    print(out.to_string(index=False))

    # Per-district disagreement between the statewide and district modes: the
    # size of the shift that uncertainty propagation actually induces.
    for group, key in (('Latino', 'pL'), ('Black', 'pB')):
        if f'{key}_dist' not in spokes.columns:
            continue
        try:
            a = parse_vectors(spokes[f'{key}_state'])
            b = parse_vectors(spokes[f'{key}_dist'])
        except (ValueError, TypeError):
            continue
        diff = np.abs(a - b)
        print(f"  {group}: per-district |p_state - p_dist| "
              f"mean {diff.mean():.4f}, 95th pct {np.percentile(diff, 95):.4f}, "
              f"max {diff.max():.4f}")

    lines = ["\\begin{tabular}{llrrrrr}", "\\toprule",
             "Group & Scoring mode & Enacted & Mean & SD & Rank & $p$ \\\\",
             "\\midrule"]
    for _, r in out.iterrows():
        lines.append(
            f"{r['group']} & {r['mode']} & {r['enacted']:.4f} & "
            f"{r['spoke_mean']:.4f} & {r['spoke_sd']:.4f} & "
            f"{int(r['rank'])}/{int(r['M'])+1} & {r['p']:.4f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_latex(os.path.join(args.outdir, 'ablation_modes.tex'),
                "\n".join(lines),
                "Opportunity scores and finite-sample ranks under the three EI "
                "weighting modes over the same spoke ensemble. The "
                "district-specific mode is the one that propagates "
                "precinct-level posterior uncertainty.",
                "tab:modes")


# ---------------------------------------------------------------- locality ---
def cmd_locality(args):
    enacted, spokes = load_scores(args.scores)
    stats = {}

    if args.plans:
        plans = pd.read_parquet(args.plans)
        spoke_cols = [c for c in plans.columns if c.startswith('spoke')]
        ref = plans['enacted'].values
        frac_enacted = np.array([(plans[c].values != ref).mean()
                                 for c in spoke_cols])
        stats['frac_precincts_moved_vs_enacted'] = frac_enacted
        if 'hub' in plans.columns:
            hub = plans['hub'].values
            stats['frac_precincts_moved_vs_hub'] = np.array(
                [(plans[c].values != hub).mean() for c in spoke_cols])
            stats['frac_enacted_moved_vs_hub'] = np.array(
                [(ref != hub).mean()])
    for col in ('frac_moved_vs_hub', 'frac_moved_vs_enacted'):
        if col in spokes.columns:
            stats.setdefault(col, spokes[col].values)

    summary = []
    for name, vals in stats.items():
        vals = np.asarray(vals, dtype=float)
        summary.append({'quantity': name, 'n': len(vals), 'mean': vals.mean(),
                        'sd': vals.std(), 'min': vals.min(),
                        'p05': np.percentile(vals, 5),
                        'p95': np.percentile(vals, 95), 'max': vals.max()})
    for col in ('cut_edges', 'county_splits'):
        if col in spokes.columns:
            v = spokes[col].astype(float).values
            summary.append({'quantity': f'{col} (spokes)', 'n': len(v),
                            'mean': v.mean(), 'sd': v.std(), 'min': v.min(),
                            'p05': np.percentile(v, 5),
                            'p95': np.percentile(v, 95), 'max': v.max()})
            if col in enacted.index:
                print(f"  enacted {col}: {enacted[col]}")

    out = pd.DataFrame(summary)
    csv_path = os.path.join(args.outdir, 'ensemble_locality.csv')
    out.to_csv(csv_path, index=False)
    print(f"  wrote {csv_path}")
    print(out.to_string(index=False))

    if 'frac_precincts_moved_vs_enacted' in stats:
        fig, ax = plt.subplots(figsize=(5.0, 3.0))
        ax.hist(stats['frac_precincts_moved_vs_enacted'], bins=40)
        ax.set_xlabel('fraction of precincts assigned to a different district '
                      'than under the enacted plan')
        ax.set_ylabel('spoke plans')
        fig.tight_layout()
        for ext in ('pdf', 'png'):
            fig.savefig(os.path.join(args.outdir, f'ensemble_locality.{ext}'),
                        dpi=200)
        print("  wrote ensemble_locality.pdf/.png")


# ------------------------------------------------------------------ ksweep ---
def cmd_ksweep(args):
    rows = []
    for cfg_path in sorted(sum([glob.glob(p) for p in args.runs], [])):
        with open(cfg_path) as fh:
            cfg = json.load(fh)
        run = cfg['run_name']
        res_path = os.path.join(os.path.dirname(cfg_path),
                                f'bc_opportunity_results_{run}.csv')
        row = {'run': run, 'k': cfg.get('k_walk_steps'),
               'M': cfg.get('M_spokes'), 'seed': cfg.get('master_seed'),
               'compactness_slack': cfg.get('compactness_slack'),
               'start_map': cfg.get('start_map'),
               'accept_fraction': cfg.get('hub_accept_fraction'),
               'moved_vs_hub_mean': cfg.get('spoke_frac_moved_vs_hub_mean'),
               'moved_vs_enacted_mean': cfg.get(
                   'spoke_frac_moved_vs_enacted_mean'),
               'runtime_min': cfg.get('total_runtime_min')}
        if os.path.exists(res_path):
            res = pd.read_csv(res_path).iloc[0]
            for label in ('L', 'B'):
                key = 'O_L' if label == 'L' else 'O_B'
                row[f'enacted_{key}'] = res.get(f'enacted_{key}')
                row[f'rank_{label}'] = res.get(f'rank_{key}')
                row[f'p_{label}'] = res.get(f'p_{key}_lower')
        else:
            print(f"  ! no results CSV beside {cfg_path}")
        rows.append(row)

    out = pd.DataFrame(rows).sort_values(['compactness_slack', 'k', 'seed'],
                                         na_position='last')
    csv_path = os.path.join(args.outdir, 'run_matrix.csv')
    out.to_csv(csv_path, index=False)
    print(f"  wrote {csv_path}")
    print(out.to_string(index=False))

    lines = ["\\begin{tabular}{rrrrrrr}", "\\toprule",
             "$k$ & $M$ & Accept.\\ frac. & Moved vs.\\ enacted & "
             "Latino rank & Latino $p$ & Black rank \\\\", "\\midrule"]
    for _, r in out.iterrows():
        def fmt(x, spec='{:.3f}'):
            return '--' if pd.isna(x) else spec.format(x)
        lines.append(
            f"{int(r['k']) if pd.notna(r['k']) else '--'} & "
            f"{int(r['M']) if pd.notna(r['M']) else '--'} & "
            f"{fmt(r['accept_fraction'])} & "
            f"{fmt(r['moved_vs_enacted_mean'])} & "
            f"{'--' if pd.isna(r.get('rank_L')) else int(r['rank_L'])} & "
            f"{fmt(r.get('p_L'), '{:.4f}')} & "
            f"{'--' if pd.isna(r.get('rank_B')) else int(r['rank_B'])} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_latex(os.path.join(args.outdir, 'run_matrix.tex'), "\n".join(lines),
                "Simulation configuration study: finite-sample rank of the "
                "enacted plan as the hub-and-spoke chain length $k$, the hub "
                "replicate, and the constraint tolerance vary. Exactness holds "
                "at every $k$; $k$ controls only how far the simulated plans "
                "travel, and hence power.",
                "tab:run-matrix")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest='cmd', required=True)

    def common(p, needs_scores=True):
        if needs_scores:
            p.add_argument('--scores', required=True,
                           help='re-scored ensemble CSV from rescore_plans.py')
        p.add_argument('--outdir', default='outputs')

    p = sub.add_parser('threshold'); common(p)
    p.add_argument('--taus', default='0.5,0.55,0.6,0.65,0.7,0.75,0.8')
    p.add_argument('--mode', default='state', choices=['state', 'equal', 'dist'])
    p.set_defaults(func=cmd_threshold)

    p = sub.add_parser('modes'); common(p)
    p.set_defaults(func=cmd_modes)

    p = sub.add_parser('locality'); common(p)
    p.add_argument('--plans', default=None,
                   help='bc_plan_assignments_<RUN>.parquet')
    p.set_defaults(func=cmd_locality)

    p = sub.add_parser('ksweep'); common(p, needs_scores=False)
    p.add_argument('--runs', nargs='+', required=True,
                   help='glob(s) matching bc_run_config_*.json')
    p.set_defaults(func=cmd_ksweep)

    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)
    args.func(args)


if __name__ == '__main__':
    main()
