# -*- coding: utf-8 -*-
"""
besag_clifford_vra_opportunity.py
==========================================

Axiom-Derived Minority Opportunity Functional
with Diversity Calibration and Besag-Clifford exact inference.

Conceptual structure
--------------------
This implementation separates the theoretical functional from the
calibration layer:

1. Canonical opportunity functional:

       O_g(pi) = sum_d p_d^g(pi)

   where p_d^g(pi) is the model-based probability that group g's
   preferred candidate wins district d under plan pi.

   This is the object justified by the axioms in the paper: anonymity,
   district additivity, monotonicity, and normalization. O_g(pi) is the
   expected number of opportunity districts.

2. Diversity-calibrated opportunity gap:

       F_g(pi) = O_g(pi) - K * m_bar_g

   where m_bar_g is the statewide CVAP share of group g. F_g(pi) is not
   a replacement for O_g(pi); it is a centered version of the canonical
   opportunity score.

3. Ensemble-standardized score:

       Z_g(pi_enacted) = (O_g(pi_enacted) - E_rho[O_g(pi)]) / sd_rho(O_g(pi))

   This calibrates the enacted plan to the state-specific opportunity
   frontier generated by the neutral ReCom ensemble.

4. Besag-Clifford exact lower-tail p-value:

       p = (# spokes with statistic <= enacted statistic + 1) / (M + 1)

   The primary test statistic is F_g, but O_g and Z_g are reported.
"""

import random as stdlib_random
import time
import os
import json as _json
import platform
import subprocess
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib
matplotlib.use('Agg')  # headless backend -- must precede pyplot import
import matplotlib.pyplot as plt
from functools import partial
import operator
import multiprocessing as mp

from texas_gerrymandering_hb4.config import TX_ELECTIONS, CANDIDATE_RACE_PARTY, PREC_COUNT_QUANTS_INPUT, INGROUP_WEIGHT_CSV_FILE, DROPPED_ELECS, STATEWIDE_RXC_EI_PREFERENCES_INPUT, RECENCY_WEIGHTS, MEAN_PREC_VOTE_COUNTS_INPUT, PRECINCT_DATASET_PARQUET, TX_LOGIT_PARAMS_CSV

# NOTE: gerrychain.random was deprecated. Per gerrychain release notes, the
# library now hooks directly into Python's stdlib `random` module, so seeding
# the stdlib `random` (already imported above as stdlib_random) controls all
# gerrychain randomness. No separate gc_random import is needed.
from gerrychain import (
    Graph, MarkovChain, GeographicPartition,
    accept, constraints, updaters, Election
)
from gerrychain.proposals import reversible_recom
from gerrychain.proposals.tree_proposals import ReversibilityError
from gerrychain.updaters import cut_edges, Tally
from gerrychain.tree import recursive_tree_part, find_balanced_edge_cuts_memoization
from collections import Counter

from run_functions import (
    compute_final_dist, compute_W2, prob_conf_conversion,
    cand_pref_outcome_sum, cand_pref_all_draws_outcomes,
    precompute_state_weights, compute_district_weights
)

# ============================================================
# USER PARAMETERS
# ============================================================
#
# Ensemble-size rationale (reviewer-defensible configuration)
# -----------------------------------------------------------
# M_SPOKES controls the *resolution* of the Besag-Clifford exact test.
# With M spokes, the minimum achievable lower-tail p-value is 1/(M+1):
#
#     M =   200  -> min p ~ 0.0050   (test pinned at floor; cannot resolve
#                                     "very extreme" from "extremely extreme")
#     M =  1000  -> min p ~ 0.0010   (standard for published redistricting
#                                     work; see Mattingly group, MGGG,
#                                     DeFord-Duchin-Solomon)
#     M = 10000  -> min p ~ 0.0001   (litigation/expert-witness grade)
#
# We adopt M=1000 as the professional default. If you have access to more
# compute (cluster / cloud) bump to 5000 or 10000; the only cost is wall
# time, not validity.
#
# L_WALK is the chain length used for BOTH the hub leg (enacted -> hub) and
# every spoke leg (hub -> spoke). These MUST be equal. The Besag-Clifford
# hub-and-spoke construction is exact only if the observed (enacted) plan and
# each spoke are the SAME number of kernel steps from the hub: then, under a
# reversible kernel, enacted | hub and spoke_i | hub are identically
# distributed (~ P^{L_WALK}(hub, .)), so {enacted, spoke_1, ..., spoke_M} are
# conditionally i.i.d. given the hub and therefore exchangeable, which is what
# makes the rank of the enacted statistic uniform under H_0. If the hub leg
# and spoke legs had different lengths, enacted ~ P^{L_hub} and spokes ~
# P^{L_spoke} would NOT be exchangeable and the p-value would not be exact.
# (This is why the previous L_HUB=2000 / L_SPOKE=500 split was incorrect: a
# longer hub leg does not add a safety margin, it breaks exactness.)
#
# Given exactness holds for ANY common L_WALK, L_WALK affects only *power*
# (how far the spokes wander from the hub) and wall time, not validity. Note
# that reversible ReCom self-loops frequently (see REVRECOM_M below), so the
# number of *accepted* moves in L_WALK steps is much smaller than L_WALK; if
# spokes look too close to the hub, raise L_WALK (keeping hub and spoke equal,
# which is automatic here since both read L_WALK).
# --- GeoSim revision: environment overrides ---------------------------------
# Every configuration knob below can be set from the environment, so the
# chain-length sweep, hub replication, tightened-constraint, and
# second-enacted-plan runs are launched from a shell script rather than by
# editing this file between runs. Unset variables reproduce exactly the
# configuration used for the original submission. The realized values are
# written to outputs/bc_run_config_<RUN_NAME>.json at the end of main().


def _env_int(name, default):
    v = os.environ.get(name)
    return default if v is None or v == "" else int(v)


def _env_float_or_none(name, default):
    v = os.environ.get(name)
    if v is None or v == "":
        return default
    return None if v.strip().lower() in ("none", "null", "off") else float(v)


def _env_str(name, default):
    v = os.environ.get(name)
    return default if v is None or v == "" else v


L_WALK    = _env_int("BC_L_WALK", 50000)
L_HUB     = L_WALK
L_SPOKE   = L_WALK

# M_SPOKES controls p-value resolution (min lower-tail p = 1/(M+1)).
#   M=1000 -> min p ~ 0.001 ; M=200 -> min p ~ 0.005.
# We use M=200. The enacted Texas plan sits FAR in the lower tail on every
# functional (the prior always-accept run put Latino at Z ~ -6 and the
# enacted F-scores are deeply negative), so a floor of 1/201 ~ 0.005 is more
# than enough to support the claim "the enacted plan is more extreme than
# every neutral alternative we drew": if the enacted rank is 1 of 201, that
# is p <= 0.005 one-sided, which clears the usual 0.01 bar. Resolving 0.001
# vs 0.005 would only matter if the enacted plan sat NEAR the boundary, which
# it does not. M=200 cuts spoke wall time 5x relative to M=1000 -- the single
# largest, validity-neutral speedup available, since reversible ReCom's cost
# is dominated by the per-proposal spanning-tree draw (see REVRECOM_M note),
# not by anything that M trades against. If a reviewer specifically demands
# 10^-3 resolution, raise this back to 1000 and budget ~5x the wall time;
# nothing else need change.
M_SPOKES  = _env_int("BC_M_SPOKES", 1000)
N_WORKERS = _env_int("BC_N_WORKERS", max(1, mp.cpu_count() - 1))
# Master seed for the whole run. -1 (the default) means "draw one at random and
# report it"; setting BC_SEED makes a run bit-for-bit reproducible, which is
# what the hub-replication study varies.
MASTER_SEED = _env_int("BC_SEED", -1)

# REVRECOM_M: the reversible-ReCom tuning constant M from Cannon, Duchin,
# Randall & Rule (2022), "Spanning Tree Methods for Sampling Graph
# Partitions" (arXiv:2210.01401). At each step reversible ReCom draws a
# uniform spanning tree on the merged district pair, enumerates balanced
# edges, and accepts with probability len(cuts)/(M * seam_length); otherwise
# it self-loops. This per-step spanning-tree draw on a large merged subgraph
# is the DOMINANT cost of the whole run (far more than any score or
# constraint evaluation), and the low acceptance probability is why the chain
# spends most steps self-looping. Neither fact is a bug -- it is the price of
# the exact-test guarantee.
#
# Choosing M is a trade-off with NO effect on validity, only on speed and
# robustness:
#   * Too small: when a merged pair yields more than M balanced edges, the
#     library raises ReversibilityError. We catch it and self-loop (see
#     run-chain code) so the job never crashes, and we COUNT how often it
#     fires. A nonzero trigger rate means the M-bound is being hit and the
#     truncation it implies could introduce a small bias, so treat a
#     non-negligible rate as a signal to RAISE M and rerun. A zero/near-zero
#     rate means the bound never bound and the test is clean.
#   * Too large: acceptance probability len(cuts)/(M*seam) shrinks, so the
#     chain self-loops even more and mixes more slowly (still valid, just
#     slower / lower power).
# M must be a fixed constant chosen in advance; adapting it online to hit a
# target acceptance rate would break reversibility. Start at 50; watch the
# reported ReversibilityError rate and accepted-move fraction from the hub
# diagnostic and adjust BEFORE the production run, then leave it fixed.
REVRECOM_M = _env_int("BC_REVRECOM_M", 20)

START_MAP  = _env_str("BC_START_MAP", 'CD')
RUN_NAME   = _env_str("BC_RUN_NAME", 'TX_BC_functional')
MODEL_MODE = _env_str("BC_MODEL_MODE", 'statewide')

# Legacy threshold-count cutoff. The threshold ablation now sweeps tau post hoc
# from the per-district probability vectors recorded for every plan, so this
# value only controls the legacy *_eff columns.
EFFECTIVENESS_CUTOFF = float(_env_str("BC_CUTOFF", "0.6"))

# ============================================================
# FIXED PARAMETERS
# ============================================================

NUM_DISTRICTS   = 38
# Population balance tolerance for ReCom proposals AND for validating the
# initial state. The enacted Texas CD map has ~1.7% top-to-bottom deviation
# under the parquet's TOTALPOP column (Census P.L. 94-171 numbers don't
# survive the precinct/CD crosswalk perfectly), so anything tighter than ~2%
# rejects the enacted map as the chain's initial state. We adopt 5%, which is
# common practice for ensemble work where the deviation is measured against
# something other than the legally-balanced reference column.
POP_TOL         = 0.05
# Compactness constraint: reject any proposal whose total cut-edges count
# exceeds COMPACTNESS_SLACK * (enacted plan's cut-edges). Cut-edges are the
# number of graph edges whose endpoints lie in different districts; lower
# values mean "more compact" districts (fewer jagged boundaries between
# adjacent districts). We use the enacted plan's count, scaled, as the
# threshold so the constraint is state-relative rather than absolute.
# Slack of 1.5 is the literature-conventional choice: tight enough to
# meaningfully constrain the null but loose enough that the chain doesn't
# get trapped near the enacted map. Set this to None to disable the
# compactness constraint (script falls back to ReCom's implicit
# spanning-tree compactness preference, which is what the paper uses).
COMPACTNESS_SLACK = _env_float_or_none("BC_COMPACTNESS_SLACK", 1.5)

# County-split constraint: reject any proposal that splits more counties
# than COUNTY_SPLITS_SLACK * (enacted plan's split-county count). A county
# is "split" if its precincts land in 2+ different districts under the
# proposed plan. This addresses the standard reviewer / opposing-expert
# objection that ensemble plans achieve high opportunity scores by
# carving counties more aggressively than any real-world map drawer
# would, ignoring communities of interest and county-level political
# boundaries that state law and tradition treat as meaningful units.
#
# Slack of 1.2 (20% looser than enacted) is the middle of the literature
# range:
#   - 1.0 (as tight as enacted): too restrictive in practice; ReCom's
#     boundary swaps frequently produce single-county-split moves and
#     the chain crawls.
#   - 1.2: the sweet spot used in most peer-reviewed work; allows the
#     chain to mix while preserving the constraint's bite.
#   - 1.5: looser; comparable to the compactness slack above.
#   - None: disables the constraint.
COUNTY_SPLITS_SLACK = _env_float_or_none("BC_COUNTY_SPLITS_SLACK", 1.5)

# Column in state_gdf that identifies each precinct's county. If this
# column isn't present, we fall back to the first 3 characters of
# GEO_ID (the Texas CNTYVTD convention is CCCxxxxx where CCC is the
# 3-digit county code).
COUNTY_COL = 'COUNTY'

# Populated in main() after score_enacted_map() returns. Worker processes
# inherit the populated values via fork(), so they are safe to read in
# _build_proposal_and_constraint from any process.
ENACTED_CUT_EDGES = None
ENACTED_COUNTY_SPLITS = None
# Enacted assignment, published as a module global in main() so forked spoke
# workers can measure how far each spoke travelled from the observed plan.
ENACTED_ASSIGNMENT = None

# Per-process counters of reversible-ReCom M-bound violations (ReversibilityError)
# and total proposal calls. Each forked worker keeps its own; the hub process
# reports its own. A nonzero ratio is a signal to raise REVRECOM_M (see the
# REVRECOM_M note above) -- it does not crash the run because we self-loop.
REVERR_COUNT = 0
PROPOSAL_COUNT = 0

PLOT_PATH       = PRECINCT_DATASET_PARQUET
DIR             = ''

# Column names match the schema produced by pipelines/data_engineering_layer
# (see schema.py: SCHEMA list).
TOT_POP         = 'TOTALPOP'
CVAP            = 'CVAP'
WCVAP           = 'WCVAP'
HCVAP           = 'HCVAP'
BCVAP           = 'BCVAP'
GEO_ID          = 'CNTYVTD'
C_X             = 'C_X'
C_Y             = 'C_Y'

if not os.path.exists(DIR + 'outputs'):
    os.mkdir(DIR + 'outputs')

# ============================================================
# DATA LOADING  (identical to besag_clifford_vra.py)
# ============================================================

print("Loading data...")

elec_data        = pd.read_csv(TX_ELECTIONS)
dropped_elecs    = pd.read_csv(DROPPED_ELECS)["Election Set"]
recency_weights  = pd.read_csv(RECENCY_WEIGHTS)
min_cand_weights = pd.read_csv(INGROUP_WEIGHT_CSV_FILE)
cand_race_table  = pd.read_csv(CANDIDATE_RACE_PARTY)
EI_statewide     = pd.read_csv(STATEWIDE_RXC_EI_PREFERENCES_INPUT)
prec_ei_df       = pd.read_csv(PREC_COUNT_QUANTS_INPUT,     dtype={'CNTYVTD': 'str'})
mean_prec_counts = pd.read_csv(MEAN_PREC_VOTE_COUNTS_INPUT, dtype={'CNTYVTD': 'str'})
logit_params     = pd.read_csv(TX_LOGIT_PARAMS_CSV)

# ---- precinct dataset ----
# tx_precincts_final.parquet is produced by pipelines/data_engineering_layer.
# Columns are canonical (see schema.py); no renaming is needed here.
state_gdf = gpd.read_parquet(PLOT_PATH)
state_gdf["CD"] = state_gdf["CD"].astype('int')

# Candidate vote columns present in the parquet (per schema.SCHEMA). These
# replace the historical TX_columns.csv list and feed the per-election
# candidate filter below.
TX_columns = [
    # 2024 General
    "TrumpR_24G", "HarrisD_24G",
    "CruzR_24G",  "AllredD_24G",
    "CraddickR_24G", "CulbertD_24G",
    # 2024 Republican Presidential Primary
    "BinkleyR_24P", "HaleyR_24P", "StuckenbergR_24P", "TrumpR_24P",
    "ChristieR_24P", "RamaswamyR_24P", "HutchinsonR_24P", "DeSantisR_24P",
    "UncommittedR_24P",
    # 2024 Democratic Presidential Primary
    "BidenD_24P", "CornejoD_24P", "LockeD_24P", "LozadaD_24P",
    "PerezD_24P", "PhillipsD_24P", "UygurD_24P", "WilliamsonD_24P",
    # 2024 Senate Primary
    "CruzR_24P", "GibsonR_24P", "LopezR_24P",
    "AllredD_24P", "GomezD_24P", "GonzalezD_24P", "GutierrezD_24P",
    "HassanD_24P", "KeoughD_24P", "PrillimanD_24P", "ShermanD_24P",
    "TchenkoD_24P",
    # 2024 Railroad Commissioner Primary
    "ClarkR_24P", "CraddickR_24P", "HowellR_24P", "MatlockR_24P", "ReyesR_24P",
    "BurchD_24P", "CulbertD_24P",
]

state_df = pd.DataFrame(state_gdf).drop(['geometry'], axis=1)

# ---- graph ----
graph = Graph.from_geodataframe(state_gdf)
graph.add_data(state_gdf)
centroids_geom = state_gdf.centroid
for node in graph.nodes():
    graph.nodes[node]["C_X"] = centroids_geom.x[node]
    graph.nodes[node]["C_Y"] = centroids_geom.y[node]

# ---- apply contiguity bridge edges (Reading A) ----
# diagnose_and_repair_graph.py writes outputs/bridge_edges.json: a list of
# edges that make every ENACTED district induce a connected subgraph WITHOUT
# changing any precinct's district assignment. This is required so the enacted
# plan is a valid starting state for reversible ReCom (which draws spanning
# trees and cannot handle a district with no spanning tree). Edges are applied
# by GEO_ID so the file is robust to row reordering. Most edges are short
# rook-adjacency repairs (true geography); a few are long, disclosed bridges
# embedding PLANC2333's intentional discontiguous metro assignments (TX CD 10,
# 11). If the file is absent the graph is used as-is and a warning is printed
# (the run will then crash on the first discontiguous-district merge).
_BRIDGE_EDGES_PATH = DIR + 'outputs/bridge_edges.json'
if os.path.exists(_BRIDGE_EDGES_PATH):
    import json as _json
    with open(_BRIDGE_EDGES_PATH) as _bf:
        _bridge_payload = _json.load(_bf)
    _geoid_to_node = {graph.nodes[n][GEO_ID]: n for n in graph.nodes()}
    _applied = 0
    _missing = 0
    _max_len = 0.0
    for _e in _bridge_payload.get("edges", []):
        _u = _geoid_to_node.get(_e["u_geoid"])
        _v = _geoid_to_node.get(_e["v_geoid"])
        if _u is None or _v is None:
            _missing += 1
            continue
        if not graph.has_edge(_u, _v):
            graph.add_edge(_u, _v)
            _applied += 1
            _max_len = max(_max_len, float(_e.get("length", 0.0)))
    print(f"Applied {_applied} contiguity bridge edges "
          f"(units: {_bridge_payload.get('units','?')}, "
          f"max length {_max_len:.3f}); {_missing} skipped (GEO_ID not found).")
else:
    print("WARNING: outputs/bridge_edges.json not found. Graph used as-is; "
          "enacted districts may be discontiguous and reversible ReCom will "
          "crash on the first such merge. Run diagnose_and_repair_graph.py "
          "--repair first.")

# ---- elections data structures ----
elecs_bool      = ~elec_data.Election.isin(list(dropped_elecs))
elec_data_trunc = elec_data[elecs_bool].reset_index(drop=True)
elec_sets       = list(set(elec_data_trunc["Election Set"]))
elections       = list(elec_data_trunc["Election"])
general_elecs   = list(elec_data_trunc[elec_data_trunc["Type"] == 'General'].Election)
primary_elecs   = list(elec_data_trunc[elec_data_trunc["Type"] == 'Primary'].Election)
runoff_elecs    = list(elec_data_trunc[elec_data_trunc["Type"] == 'Runoff'].Election)
elec_cand_list  = TX_columns

elec_set_dict = {}
for elec_set in elec_sets:
    sub = elec_data_trunc[elec_data_trunc["Election Set"] == elec_set]
    elec_set_dict[elec_set] = dict(zip(sub.Type, sub.Election))

elec_match_dict = dict(zip(elec_data_trunc["Election"], elec_data_trunc["Election Set"]))

# Explicit election -> candidate mapping.
#
# The historical filter that lived here used substring matching: it assumed
# candidate column names contained the election label as a substring (e.g.
# candidate "Foo_USSEN_24P_R" for election "USSEN_24P"). The current parquet
# schema (see line 140-142) names candidate columns Name+Party_Stage with no
# office tag (e.g. "CruzR_24P"), so substring matching against election labels
# like "24P_SenR" or "24G_President" returns the empty list for every election
# and `dist_elec_results[elec][i]` is empty downstream -> ValueError in max().
#
# Because candidate columns no longer carry the office, the mapping cannot be
# derived from string surgery alone; we list it explicitly. Update this dict
# whenever TX_columns or elec_data adds/removes elections or candidates.
ELECTION_TO_CANDIDATES = {
    "24G_President":  ["TrumpR_24G", "HarrisD_24G"],
    "24P_PresR":      ["BinkleyR_24P", "HaleyR_24P", "StuckenbergR_24P", "TrumpR_24P",
                       "ChristieR_24P", "RamaswamyR_24P", "HutchinsonR_24P",
                       "DeSantisR_24P", "UncommittedR_24P"],
    "24P_PresD":      ["BidenD_24P", "CornejoD_24P", "LockeD_24P", "LozadaD_24P",
                       "PerezD_24P", "PhillipsD_24P", "UygurD_24P", "WilliamsonD_24P"],
    "24G_US_Sen":     ["CruzR_24G", "AllredD_24G"],
    "24P_SenR":       ["CruzR_24P", "GibsonR_24P", "LopezR_24P"],
    "24P_SenD":       ["AllredD_24P", "GomezD_24P", "GonzalezD_24P", "GutierrezD_24P",
                       "HassanD_24P", "KeoughD_24P", "PrillimanD_24P", "ShermanD_24P",
                       "TchenkoD_24P"],
    "24G_RR_Comm_1":  ["CraddickR_24G", "CulbertD_24G"],
    "24P_RRCR":       ["ClarkR_24P", "CraddickR_24P", "HowellR_24P",
                       "MatlockR_24P", "ReyesR_24P"],
    "24P_RRCD":       ["BurchD_24P", "CulbertD_24P"],
}

candidates = {}
for elec in elections:
    if elec not in ELECTION_TO_CANDIDATES:
        raise KeyError(
            f"No candidate mapping for election {elec!r}. Update "
            f"ELECTION_TO_CANDIDATES with its candidate columns from TX_columns."
        )
    cands = ELECTION_TO_CANDIDATES[elec]
    missing = [c for c in cands if c not in elec_cand_list]
    if missing:
        raise KeyError(
            f"Candidates {missing} listed for election {elec!r} are not in "
            f"TX_columns / parquet schema. Either fix TX_columns or update "
            f"ELECTION_TO_CANDIDATES."
        )
    if elec in general_elecs:
        cands = cands[:2]
    candidates[elec] = dict(zip(range(len(cands)), cands))

# Strip the office suffix from CANDIDATE_RACE_PARTY's "Candidates" keys so the
# race lookup uses the same Name+Party_Stage form that the rest of the pipeline
# (parquet columns, EI table, gerrychain Elections) uses. Mirrors the same
# transformation applied to cand_party_dict in run_functions.compute_final_dist.
cand_race_dict        = {
    "_".join(full_key.split("_")[:2]): race
    for full_key, race in cand_race_table.set_index("Candidates")["Race"].items()
}
min_cand_weights_dict = {k: min_cand_weights.to_dict()[k][0]
                          for k in min_cand_weights.to_dict().keys()}

elec_years     = [elec_data_trunc.loc[elec_data_trunc["Election Set"] == es, 'Year']
                  .values[0].astype(str) for es in elec_sets]
recency_scores = [recency_weights[yr][0] for yr in elec_years]
recency_W1     = np.tile(recency_scores, (NUM_DISTRICTS, 1)).transpose()

(black_weight_state,  hisp_weight_state,  neither_weight_state,
 black_weight_equal,  hisp_weight_equal,  neither_weight_equal,
 black_pref_cands_prim_state,   hisp_pref_cands_prim_state,
 black_pref_cands_runoffs_state, hisp_pref_cands_runoffs_state) = \
    precompute_state_weights(
        NUM_DISTRICTS, elec_sets, elec_set_dict, recency_W1, EI_statewide,
        primary_elecs, runoff_elecs, elec_match_dict,
        min_cand_weights_dict, cand_race_dict
    )

demogs    = ['BCVAP', 'HCVAP']
bases     = {col.split('.')[0] + '.' + col.split('.')[1]
             for col in prec_ei_df.columns
             if col[:5] in demogs and 'abstain' not in col
             and not any(x in col for x in general_elecs)}
base_dict = {b: (b.split('.')[0].split('_')[0],
                 '_'.join(b.split('.')[1].split('_')[:-2]))
             for b in bases}
outcomes = {val: [] for val in base_dict.values()}
for b in bases:
    outcomes[base_dict[b]].append(b)

precs               = list(state_gdf[GEO_ID])
prec_draws_outcomes = cand_pref_all_draws_outcomes(prec_ei_df, precs, bases, outcomes)

print("Data loaded.")

# ============================================================
# STATEWIDE DEMOGRAPHIC FRACTIONS  (new)
# ============================================================

def _compute_statewide_fractions(gdf):
    """
    Compute statewide minority CVAP fractions from the shapefile.

    Called once at module load. Results stored as module-level
    constants M_BAR_B, M_BAR_L, M_BAR_COMBINED.

    Returns
    -------
    m_bar_B        : float  Black CVAP / Total CVAP
    m_bar_L        : float  Latino CVAP / Total CVAP
    m_bar_combined : float  (Black + Latino) CVAP / Total CVAP
    """
    total_cvap    = gdf[CVAP].sum()
    black_cvap    = gdf[BCVAP].sum()
    hisp_cvap     = gdf[HCVAP].sum()
    combined_cvap = black_cvap + hisp_cvap

    m_bar_B        = black_cvap    / total_cvap
    m_bar_L        = hisp_cvap     / total_cvap
    m_bar_combined = combined_cvap  / total_cvap

    print(f"\nStatewide CVAP fractions:")
    print(f"  m_bar_B        = {m_bar_B:.4f}  ({100*m_bar_B:.2f}%)")
    print(f"  m_bar_L        = {m_bar_L:.4f}  ({100*m_bar_L:.2f}%)")
    print(f"  m_bar_combined = {m_bar_combined:.4f}  ({100*m_bar_combined:.2f}%)")
    print(f"  Proportional seat targets:")
    print(f"    Black    : {NUM_DISTRICTS * m_bar_B:.2f}")
    print(f"    Latino   : {NUM_DISTRICTS * m_bar_L:.2f}")
    print(f"    Combined : {NUM_DISTRICTS * m_bar_combined:.2f}")

    return m_bar_B, m_bar_L, m_bar_combined


M_BAR_B, M_BAR_L, M_BAR_COMBINED = _compute_statewide_fractions(state_gdf)

# ============================================================
# UPDATERS  (identical to besag_clifford_vra.py)
# ============================================================

def final_elec_model(partition):
    """
    Elections model updater. Identical to besag_clifford_vra.py.

    Computes per-district raw effectiveness scores for minority-preferred
    candidates under statewide, equal, and district EI weighting modes.

    Returns
    -------
    (final_state_prob, final_equal_prob, final_dist_prob)
    Each: {district_index: (hisp_prob, black_prob, neither_prob)}
    These are the uncalibrated raw effectiveness scores s_unw / s_state /
    s_dist as defined in Becker, Duchin, Gold, Hirsch (2021) Section 4.3 --
    weighted share of election sets in which the minority-preferred candidate
    succeeded. Logistic calibration (Sec 4.4) is not applied; see the comment
    above the compute_final_dist call sites for rationale.
    """
    if partition.parent is not None:
        dict1 = dict(partition.parent.assignment)
        dict2 = dict(partition.assignment)
        differences = (
            set([dict1[k] for k in dict1 if dict1[k] != dict2[k]]) |
            set([dict2[k] for k in dict2 if dict1[k] != dict2[k]])
        )
        dist_changes = sorted(differences)
    else:
        dist_changes = range(NUM_DISTRICTS)

    order = [x for x in partition.parts]

    dist_elec_results = {}
    for elec in elections:
        cands = candidates[elec]
        outcome_list = [dict(zip(order, partition[elec].percents(cand)))
                        for cand in cands.keys()]
        dist_elec_results[elec] = {
            d: {cands[i]: outcome_list[i][d] for i in cands.keys()}
            for d in range(NUM_DISTRICTS)
        }

    map_winners = pd.DataFrame(columns=dist_changes)
    map_winners["Election"]      = elections
    map_winners["Election Set"]  = elec_data_trunc["Election Set"]
    map_winners["Election Type"] = elec_data_trunc["Type"]
    for i in dist_changes:
        map_winners[i] = [
            max(dist_elec_results[elec][i].items(), key=operator.itemgetter(1))[0]
            for elec in elections
        ]

    # statewide mode
    # NOTE: return_raw=True scores against the uncalibrated raw effectiveness
    # scores from Becker, Duchin, Gold, Hirsch (2021) Section 4.3 -- "weighted
    # share of elections won by the candidate of choice." Calibration (Sec 4.4)
    # is intentionally disabled here because it requires district-level ground
    # truth across multiple election cycles to fit a non-degenerate logit, and
    # the statewide-only benchmarks available to us produce a degenerate
    # (perfectly separable) fit. Document this decision in the methods section.
    final_state_prob_dict = compute_final_dist(
        map_winners, black_pref_cands_prim_state, black_pref_cands_runoffs_state,
        hisp_pref_cands_prim_state, hisp_pref_cands_runoffs_state,
        neither_weight_state, black_weight_state, hisp_weight_state,
        dist_elec_results, dist_changes, cand_race_table, NUM_DISTRICTS,
        candidates, elec_sets, elec_set_dict, "statewide", partition,
        logit_params, logit=False, return_raw=True,
    )

    # equal mode
    final_equal_prob_dict = compute_final_dist(
        map_winners, black_pref_cands_prim_state, black_pref_cands_runoffs_state,
        hisp_pref_cands_prim_state, hisp_pref_cands_runoffs_state,
        neither_weight_equal, black_weight_equal, hisp_weight_equal,
        dist_elec_results, dist_changes, cand_race_table, NUM_DISTRICTS,
        candidates, elec_sets, elec_set_dict, "equal", partition,
        logit_params, logit=False, return_raw=True,
    )

    # district mode
    (black_weight_dist,  hisp_weight_dist,  neither_weight_dist,
     black_pref_cands_prim_dist,   black_pref_cands_runoffs_dist,
     hisp_pref_cands_prim_dist,    hisp_pref_cands_runoffs_dist) = \
        compute_district_weights(
            dist_changes, elec_sets, elec_set_dict, state_gdf, partition,
            prec_draws_outcomes, GEO_ID, primary_elecs, runoff_elecs,
            elec_match_dict, bases, outcomes, recency_W1,
            cand_race_dict, min_cand_weights_dict,
            ei_geo_ids=list(prec_ei_df[GEO_ID]),
        )

    final_dist_prob_dict = compute_final_dist(
        map_winners, black_pref_cands_prim_dist, black_pref_cands_runoffs_dist,
        hisp_pref_cands_prim_dist, hisp_pref_cands_runoffs_dist,
        neither_weight_dist, black_weight_dist, hisp_weight_dist,
        dist_elec_results, dist_changes, cand_race_table, NUM_DISTRICTS,
        candidates, elec_sets, elec_set_dict, 'district', partition,
        logit_params, logit=False, return_raw=True,
    )

    if partition.parent is None:
        final_state_prob = {k: final_state_prob_dict[k] for k in sorted(final_state_prob_dict)}
        final_equal_prob = {k: final_equal_prob_dict[k] for k in sorted(final_equal_prob_dict)}
        final_dist_prob  = {k: final_dist_prob_dict[k]  for k in sorted(final_dist_prob_dict)}
    else:
        final_state_prob = partition.parent["final_elec_model"][0].copy()
        final_equal_prob = partition.parent["final_elec_model"][1].copy()
        final_dist_prob  = partition.parent["final_elec_model"][2].copy()
        for i in dist_changes:
            final_state_prob[i] = final_state_prob_dict[i]
            final_equal_prob[i] = final_equal_prob_dict[i]
            final_dist_prob[i]  = final_dist_prob_dict[i]

    return final_state_prob, final_equal_prob, final_dist_prob



# ============================================================
# AXIOM-DERIVED AND CALIBRATED OPPORTUNITY FUNCTIONALS
# ============================================================

def compute_opportunity_scores(prob_dict,
                               m_bar_B, m_bar_L, m_bar_combined,
                               K=NUM_DISTRICTS):
    """
    Compute both the canonical opportunity functional O(pi) and
    its diversity-calibrated version F(pi).

    Canonical functional, justified by the axioms in the paper:
        O_g(pi) = sum_d p_d^g(pi)

    Diversity-calibrated gap:
        F_g(pi) = O_g(pi) - K * m_bar_g

    Coalition version:
        O_joint(pi) = sum_d max(p_d^B(pi), p_d^L(pi))
        F_joint(pi) = O_joint(pi) - K * m_bar_combined
    """
    if "N/A" in prob_dict.values():
        return {
            'O_B': float('nan'), 'O_L': float('nan'), 'O_joint': float('nan'),
            'F_B': float('nan'), 'F_L': float('nan'), 'F_joint': float('nan'),
            'baseline_B': K * m_bar_B,
            'baseline_L': K * m_bar_L,
            'baseline_joint': K * m_bar_combined,
        }

    p_B_list, p_L_list = [], []
    for d in sorted(prob_dict.keys()):
        hisp_prob, black_prob, neither_prob = prob_dict[d]
        p_L_list.append(hisp_prob)
        p_B_list.append(black_prob)

    p_B_arr = np.array(p_B_list, dtype=float)
    p_L_arr = np.array(p_L_list, dtype=float)

    O_B = float(p_B_arr.sum())
    O_L = float(p_L_arr.sum())
    O_joint = float(np.maximum(p_B_arr, p_L_arr).sum())

    baseline_B = float(K * m_bar_B)
    baseline_L = float(K * m_bar_L)
    baseline_joint = float(K * m_bar_combined)

    return {
        'O_B': O_B,
        'O_L': O_L,
        'O_joint': O_joint,
        'F_B': O_B - baseline_B,
        'F_L': O_L - baseline_L,
        'F_joint': O_joint - baseline_joint,
        'baseline_B': baseline_B,
        'baseline_L': baseline_L,
        'baseline_joint': baseline_joint,
    }


# Backwards-compatible alias. Existing calls will still work, but the new
# implementation should use compute_opportunity_scores() so O(pi) is retained.
def compute_opportunity_functional(prob_dict,
                                   m_bar_B, m_bar_L, m_bar_combined,
                                   K=NUM_DISTRICTS):
    scores = compute_opportunity_scores(
        prob_dict, m_bar_B, m_bar_L, m_bar_combined, K
    )
    return scores['F_B'], scores['F_L'], scores['F_joint']


def _functional_score_from_partition(partition):
    """
    Extract O_B, O_L, O_joint and F_B, F_L, F_joint from a partition.

    O(pi) is the axiom-derived theoretical functional.
    F(pi) is the diversity-calibrated score used for the primary
    lower-tail Besag-Clifford test.
    """
    final_state_prob, final_equal_prob, final_dist_prob = \
        partition["final_elec_model"]

    prob_dict = (final_state_prob if MODEL_MODE == 'statewide' else
                 final_equal_prob if MODEL_MODE == 'equal'     else
                 final_dist_prob)

    scores = compute_opportunity_scores(
        prob_dict, M_BAR_B, M_BAR_L, M_BAR_COMBINED
    )

    if "N/A" not in prob_dict.values():
        hisp_eff  = sum(1 for v in prob_dict.values()
                        if v[0] >= EFFECTIVENESS_CUTOFF)
        black_eff = sum(1 for v in prob_dict.values()
                        if v[1] >= EFFECTIVENESS_CUTOFF)
        distinct  = len(
            set(d for d, v in prob_dict.items() if v[0] >= EFFECTIVENESS_CUTOFF) |
            set(d for d, v in prob_dict.items() if v[1] >= EFFECTIVENESS_CUTOFF)
        )
    else:
        hisp_eff = black_eff = distinct = float('nan')

    # --- GeoSim revision ----------------------------------------------------
    # Record, for every plan, (a) the aggregate scores under ALL three EI
    # weighting modes and (b) the raw per-district win-probability vectors.
    # (a) makes the point-estimate-versus-uncertainty-propagation comparison a
    # by-product of the same ensemble instead of a separate run; (b) lets any
    # opportunity threshold tau be swept post hoc without regenerating the
    # ensemble. The updater already computes all three dictionaries at every
    # step, so this costs nothing beyond the CSV columns.
    extra = {}
    for tag, pdict in (('state', final_state_prob),
                       ('equal', final_equal_prob),
                       ('dist',  final_dist_prob)):
        if "N/A" in pdict.values():
            for key in ('O_B', 'O_L', 'F_B', 'F_L'):
                extra[f'{key}_{tag}'] = float('nan')
            extra[f'pL_{tag}'] = extra[f'pB_{tag}'] = ''
            continue
        s = compute_opportunity_scores(pdict, M_BAR_B, M_BAR_L, M_BAR_COMBINED)
        for key in ('O_B', 'O_L', 'F_B', 'F_L'):
            extra[f'{key}_{tag}'] = s[key]
        ds = sorted(pdict.keys())
        extra[f'pL_{tag}'] = _json.dumps([round(float(pdict[d][0]), 6) for d in ds])
        extra[f'pB_{tag}'] = _json.dumps([round(float(pdict[d][1]), 6) for d in ds])

    return {
        **scores,
        **extra,
        'hisp_eff': hisp_eff,
        'black_eff': black_eff,
        'distinct_eff': distinct,
    }

# ============================================================
# CHAIN INFRASTRUCTURE  (identical to besag_clifford_vra.py)
# ============================================================

class CountySplitUpdater:
    """Cached, incremental updater for the number of split counties.

    Returns a dict ``{"count": int, "ccd": {county: Counter(district -> n)}}``.
    A county is "split" if its precincts occupy 2+ distinct districts.

    On the initial state (``partition.parent is None``) it scans every
    precinct once. On every subsequent state it reads the parent's cached
    ``ccd``, applies only ``partition.flips`` (the handful of precincts
    reversible ReCom actually moved), and adjusts the split count for just the
    touched counties. This keeps the per-call cost proportional to the number
    of flipped precincts rather than O(all precincts).

    Note: this updater only runs when something reads ``partition["county_splits"]``.
    In this pipeline that read happens in the feasibility wrapper, i.e. only on
    candidates that survived reversible ReCom's internal acceptance. The bulk
    of the run's cost is the spanning-tree draw inside reversible ReCom, which
    this updater does not touch; the incremental form is a modest tidy-up, not
    the main lever. (The main lever is M_SPOKES.) Validated bit-for-bit against
    the brute-force scan over long chains.
    """

    def __init__(self, county_of):
        self.county_of = county_of

    def _is_split(self, counter):
        return sum(1 for n in counter.values() if n > 0) >= 2

    def __call__(self, partition):
        parent = partition.parent
        if parent is None:
            ccd = {}
            for node, dist in partition.assignment.items():
                cty = self.county_of(partition.graph.nodes[node])
                ccd.setdefault(cty, Counter())[dist] += 1
            count = sum(1 for c in ccd.values() if self._is_split(c))
            return {"count": count, "ccd": ccd}

        prev = parent["county_splits"]
        ccd = dict(prev["ccd"])            # shallow-copy outer mapping
        count = prev["count"]
        flips = partition.flips or {}

        # copy-on-write only the counties a flipped precinct belongs to
        touched = set()
        for node in flips:
            cty = self.county_of(partition.graph.nodes[node])
            if cty not in touched:
                ccd[cty] = prev["ccd"][cty].copy()
                touched.add(cty)

        for node, new_dist in flips.items():
            cty = self.county_of(partition.graph.nodes[node])
            old_dist = parent.assignment[node]
            c = ccd[cty]
            c[old_dist] -= 1
            if c[old_dist] == 0:
                del c[old_dist]
            c[new_dist] += 1

        for cty in touched:
            before = self._is_split(prev["ccd"][cty])
            after = self._is_split(ccd[cty])
            if after and not before:
                count += 1
            elif before and not after:
                count -= 1

        return {"count": count, "ccd": ccd}


def _build_updaters():
    my_updaters = {
        "population": updaters.Tally(TOT_POP, alias="population"),
        "CVAP":       updaters.Tally(CVAP,    alias="CVAP"),
        "WCVAP":      updaters.Tally(WCVAP,   alias="WCVAP"),
        "HCVAP":      updaters.Tally(HCVAP,   alias="HCVAP"),
        "BCVAP":      updaters.Tally(BCVAP,   alias="BCVAP"),
        "Sum_CX":     updaters.Tally(C_X,     alias="Sum_CX"),
        "Sum_CY":     updaters.Tally(C_Y,     alias="Sum_CY"),
        "cut_edges":  cut_edges,
        "county_splits": CountySplitUpdater(_node_county),
        "final_elec_model": final_elec_model,
    }
    benchmark = [
        Election("PRES24",  {"Democratic": 'HarrisD_24G',
                              "Republican": 'TrumpR_24G'},      alias="PRES24"),
        Election("SEN24",   {"Democratic": 'AllredD_24G',
                              "Republican": 'CruzR_24G'},       alias="SEN24"),
        Election("RRC24_1", {"Democratic": 'CulbertD_24G',
                              "Republican": 'CraddickR_24G'},   alias="RRC24_1"),
    ]
    my_updaters.update({e.name: e for e in benchmark})
    my_updaters.update({e.name: e for e in [Election(j, candidates[j]) for j in elections]})
    return my_updaters


def _node_county(node_data):
    """Extract a county identifier from a graph node's data dict.

    Prefers the explicit COUNTY_COL if present in the node's attributes;
    otherwise falls back to the first 3 characters of GEO_ID, which under
    the Texas CNTYVTD convention is the 3-digit county code. The fallback
    keeps the script working on parquet vintages that don't carry an
    explicit county column.
    """
    if COUNTY_COL is not None and COUNTY_COL in node_data:
        return node_data[COUNTY_COL]
    return node_data[GEO_ID][:3]


def _count_county_splits(partition):
    """Number of counties whose precincts span 2+ districts under this plan.

    O(N) in the number of precincts; called once per proposal evaluation,
    which is acceptable in the same way the cut_edges scan is acceptable.
    A faster cached-updater version is possible if profiling shows this is
    a bottleneck, but for the current run sizes the simple form is fine.
    """
    county_to_districts = {}
    for node, district in partition.assignment.items():
        county = _node_county(partition.graph.nodes[node])
        county_to_districts.setdefault(county, set()).add(district)
    return sum(1 for ds in county_to_districts.values() if len(ds) >= 2)


def _build_proposal_and_constraint(initial_partition):
    """Build the reversible-ReCom proposal for the Besag-Clifford construction.

    Returns (proposal, chain_constraints) where:

    * ``proposal`` is reversible ReCom (Cannon et al. 2022), which is
      reversible with respect to the spanning-tree distribution on
      population-balanced K-partitions. This is the property the
      Besag-Clifford exact test requires; plain ReCom with always-accept is
      NOT reversible w.r.t. any known target and cannot support the exact
      p-value.

    * ``chain_constraints`` is intentionally EMPTY ``[]``. Hard constraints
      (population, compactness, county splits) are enforced INSIDE the
      proposal as self-loops -- if a reversible-ReCom move would leave the
      feasible set, the proposal returns the current state instead.

      This is the crucial correctness point. gerrychain's MarkovChain, when a
      proposal fails a Validator in ``constraints``, RE-DRAWS a new proposal
      (it does not increment the step counter and does not stay put). That
      "rejection by resampling" turns the effective kernel into
      P(x, .)/Z(x) with an x-dependent normalizer Z(x), which is NOT
      reversible and would silently void the exact test. Applying the same
      constraints as self-loops instead -- Q(x,y)=P(x,y) for feasible y!=x,
      with all infeasible mass folded onto Q(x,x) -- preserves detailed
      balance w.r.t. the spanning-tree distribution RESTRICTED to the
      feasible set. The enacted plan is feasible by construction (the
      thresholds are slack multiples of the enacted plan's own counts), so it
      lies in the support; the null is then "the spanning-tree distribution
      conditioned on the compactness and county-split feasible set," which
      should be stated as such in the paper.
    """
    total_pop = state_gdf[TOT_POP].sum()
    ideal_pop = total_pop / NUM_DISTRICTS

    base_proposal = partial(
        reversible_recom,
        pop_col=TOT_POP,
        pop_target=ideal_pop,
        epsilon=POP_TOL,
        balance_edge_fn=find_balanced_edge_cuts_memoization,
        M=REVRECOM_M,
        # repeat_until_valid MUST stay False. Setting it True makes the
        # proposal re-draw until it finds a non-self-loop move, which removes
        # exactly the self-loops that reversibility depends on -- the same
        # failure mode as resampling-based Validators, just inside the
        # proposal. Leave it False.
        repeat_until_valid=False,
    )

    # Feasibility thresholds, closed over by the self-loop wrapper below.
    pop_lo = ideal_pop * (1.0 - POP_TOL)
    pop_hi = ideal_pop * (1.0 + POP_TOL)

    max_cut_edges = (int(COMPACTNESS_SLACK * ENACTED_CUT_EDGES)
                     if (COMPACTNESS_SLACK is not None
                         and ENACTED_CUT_EDGES is not None) else None)
    max_county_splits = (int(COUNTY_SPLITS_SLACK * ENACTED_COUNTY_SPLITS)
                         if (COUNTY_SPLITS_SLACK is not None
                             and ENACTED_COUNTY_SPLITS is not None) else None)

    def _feasible(part):
        # Population: reversible ReCom already produces splits within epsilon,
        # so this almost never bites; enforced defensively so no infeasible
        # state can ever slip through and so the feasible set is stated
        # explicitly. A self-loop here is reversibility-preserving.
        pops = part["population"].values()
        if any(p < pop_lo or p > pop_hi for p in pops):
            return False
        if max_cut_edges is not None and len(part["cut_edges"]) > max_cut_edges:
            return False
        if (max_county_splits is not None
                and part["county_splits"]["count"] > max_county_splits):
            # Reads the cached, incremental CountySplitUpdater (O(flips)),
            # not the O(all-precincts) brute scan.
            return False
        return True

    def reversible_proposal(part):
        # Count every proposal, and catch the M-bound ReversibilityError that
        # reversible ReCom raises when a merged pair yields more than
        # REVRECOM_M balanced edges (or when the acceptance prob would exceed
        # 1). The reversibility-preserving response is to self-loop: return
        # the current state unchanged. We tally these so the run can report
        # how often the M-bound bound; a non-negligible rate means REVRECOM_M
        # is too small and should be raised (see its note above). Without this
        # catch the job would crash on the first violation.
        global REVERR_COUNT, PROPOSAL_COUNT
        PROPOSAL_COUNT += 1
        try:
            cand = base_proposal(part)
        except ReversibilityError:
            REVERR_COUNT += 1
            return part
        except IndexError:
            # Wilson's-algorithm spanning-tree draw hit a node with no
            # neighbors inside the merged subgraph -- an isolated vertex. This
            # happens when a merged district pair contains a precinct whose
            # only adjacencies route outside the pair (a "district island"),
            # which in turn means the enacted plan has a discontiguous district
            # OR the adjacency graph has a degree-0 node. We self-loop so the
            # job does not crash, but UNLIKE the reversibility self-loops above
            # this is NOT a clean fix: a precinct that is isolated within its
            # district makes that district induce no spanning tree, so the
            # enacted plan sits OUTSIDE the support of the spanning-tree target
            # distribution -- the distribution the Besag-Clifford rank test is
            # defined against. A non-negligible rate here means the p-value is
            # ill-posed until the graph is repaired. Run
            # diagnose_and_repair_graph.py to find and fix the offending
            # precincts BEFORE trusting any result. The counter below shares
            # REVERR_COUNT only for the printed rate; the warning text
            # distinguishes the two causes.
            REVERR_COUNT += 1
            return part
        # If reversible ReCom self-looped internally, cand is `part` (or an
        # identical assignment) and is trivially feasible. If cand is a
        # genuine move that leaves the feasible set, fold it onto a self-loop
        # by returning part.
        if _feasible(cand):
            return cand
        return part

    # Empty constraints: all hard constraints live in the proposal as
    # self-loops (see docstring). Do NOT add Validators here.
    chain_constraints = []

    return reversible_proposal, chain_constraints


def _run_chain_get_endpoint(start_assignment, n_steps, seed):
    """Run reversible ReCom for n_steps. Returns plain-dict assignment of the
    final state.

    accept=always_accept is correct here: reversibility lives in the proposal
    itself (reversible ReCom self-loops to balance the kernel, and our wrapper
    folds constraint violations onto additional self-loops), so the chain
    simply takes whatever the proposal returns at each step. There is no
    Metropolis correction to apply on top.
    """
    stdlib_random.seed(seed)
    my_updaters = _build_updaters()
    init_part   = GeographicPartition(graph=graph,
                                      assignment=start_assignment,
                                      updaters=my_updaters)
    proposal, chain_constraints = _build_proposal_and_constraint(init_part)
    chain = MarkovChain(
        proposal=proposal,
        constraints=chain_constraints,
        accept=accept.always_accept,
        initial_state=init_part,
        total_steps=n_steps,
    )
    endpoint = init_part
    for step in chain:
        endpoint = step
    return dict(endpoint.assignment)


# ============================================================
# STEP 1 — Score the enacted map
# ============================================================


def score_enacted_map():
    print("\n=== Scoring enacted map ===")
    total_pop = state_gdf[TOT_POP].sum()
    ideal_pop = total_pop / NUM_DISTRICTS

    if START_MAP == 'new_seed':
        assignment = recursive_tree_part(graph, range(NUM_DISTRICTS),
                                         ideal_pop, TOT_POP, POP_TOL, 3)
    else:
        # START_MAP names a graph-node attribute whose values are district
        # labels (e.g. the parquet's "CD" column carries Texas's real
        # congressional district numbers 1..NUM_DISTRICTS). Downstream code in
        # this script and in run_functions.compute_final_dist is written for
        # 0-indexed labels (range(NUM_DISTRICTS) is used to iterate districts
        # and to build DataFrame columns), so we remap the source labels to
        # 0..NUM_DISTRICTS-1 here at the boundary. This means "district k" in
        # all downstream outputs corresponds to the (k+1)-th smallest real
        # district label in the source column.
        raw_labels = sorted({int(graph.nodes[n][START_MAP]) for n in graph.nodes()})
        if len(raw_labels) != NUM_DISTRICTS:
            raise ValueError(
                f"START_MAP column {START_MAP!r} has {len(raw_labels)} unique "
                f"district labels, expected NUM_DISTRICTS={NUM_DISTRICTS}."
            )
        label_to_idx = {label: idx for idx, label in enumerate(raw_labels)}
        assignment = {n: label_to_idx[int(graph.nodes[n][START_MAP])]
                      for n in graph.nodes()}

    my_updaters       = _build_updaters()
    enacted_partition = GeographicPartition(graph=graph,
                                            assignment=assignment,
                                            updaters=my_updaters)

    scores = _functional_score_from_partition(enacted_partition)

    print(f"\n  Enacted map scores ({MODEL_MODE} mode):")
    print("  Canonical axiom-derived opportunity scores O(pi):")
    print(f"    O_B     = {scores['O_B']:.4f} expected Black opportunity districts")
    print(f"    O_L     = {scores['O_L']:.4f} expected Latino opportunity districts")

    print("\n  Diversity-calibrated opportunity gaps F(pi) = O(pi) - K*m_bar:")
    print(f"    F_B     = {scores['F_B']:+.4f} districts "
          f"(baseline: {scores['baseline_B']:.2f})")
    print(f"    F_L     = {scores['F_L']:+.4f} districts "
          f"(baseline: {scores['baseline_L']:.2f})")

    print(f"\n  Legacy threshold counts (cutoff = {EFFECTIVENESS_CUTOFF}):")
    print(f"    Latino-effective : {scores['hisp_eff']}")
    print(f"    Black-effective  : {scores['black_eff']}")
    print(f"    Distinct         : {scores['distinct_eff']}")

    return scores, enacted_partition


# ============================================================
# STEP 2 — Hub chain  (identical to besag_clifford_vra.py)
# ============================================================


def run_hub_chain(enacted_partition):
    """
    Run the chain forward L_HUB steps from the enacted map to reach hub X*.

    Because reversible ReCom is reversible with respect to the spanning-tree
    distribution, running it forward L_HUB steps from the enacted plan is
    distributionally equivalent to running the reverse kernel L_HUB steps.
    That is what lets the enacted plan play the role of one spoke off the hub:
    the hub is L_HUB reverse-steps "behind" the enacted plan, and each spoke is
    L_SPOKE forward-steps "ahead" of the hub. Exactness requires L_HUB ==
    L_SPOKE (both are L_WALK here), so the enacted plan and every spoke are the
    same number of steps from the hub and hence exchangeable under H_0.

    Also prints the realized accepted-move fraction (1 - self-loop rate). This
    is a diagnostic to REPORT, not a knob to tune mid-run: REVRECOM_M and
    L_WALK are fixed in advance, and the accepted-move fraction just tells you
    whether they were generous enough for the spokes to travel.
    """
    print(f"\n=== Running hub chain ({L_HUB} steps) ===")
    t0       = time.time()
    hub_seed = stdlib_random.randint(0, 10**9)
    stdlib_random.seed(hub_seed)

    proposal, chain_constraints = _build_proposal_and_constraint(enacted_partition)
    chain = MarkovChain(
        proposal=proposal,
        constraints=chain_constraints,
        accept=accept.always_accept,
        initial_state=enacted_partition,
        total_steps=L_HUB,
    )
    hub_partition = enacted_partition
    prev_assignment = dict(enacted_partition.assignment)
    accepted_moves = 0
    n_seen = 0
    for step in chain:
        cur_assignment = dict(step.assignment)
        if n_seen > 0 and cur_assignment != prev_assignment:
            accepted_moves += 1
        prev_assignment = cur_assignment
        n_seen += 1
        hub_partition = step

    transitions = max(1, n_seen - 1)
    accept_frac = accepted_moves / transitions
    reverr_rate = (REVERR_COUNT / PROPOSAL_COUNT) if PROPOSAL_COUNT else 0.0
    hub_assignment = dict(hub_partition.assignment)
    hub_elapsed = time.time() - t0
    print(f"  Hub reached in {hub_elapsed:.1f}s.")
    print(f"  Accepted-move fraction: {accept_frac:.3f} "
          f"({accepted_moves} moves / {transitions} steps; "
          f"REVRECOM_M={REVRECOM_M}, L_WALK={L_WALK}).")
    print(f"  Reversibility M-bound hit rate: {reverr_rate:.4f} "
          f"({REVERR_COUNT}/{PROPOSAL_COUNT} proposals self-looped on the "
          f"M-bound).")
    if reverr_rate > 0.001:
        print("  WARNING: reversible ReCom self-looped on the M-bound and/or "
              "an isolated-node (IndexError) failure. M-bound self-loops are "
              "safe but a high rate suggests raising REVRECOM_M. Isolated-node "
              "self-loops are MORE serious: they mean the enacted plan likely "
              "has a discontiguous district, so it sits outside the support of "
              "the spanning-tree target and the exact p-value is ill-posed. "
              "Run diagnose_and_repair_graph.py to check and repair the graph "
              "BEFORE trusting any result.")
    # GeoSim revision: the accepted-move fraction is the quantity that makes
    # "k = L_WALK steps" interpretable -- it converts nominal steps into
    # realized recombination moves, which is what a reader needs in order to
    # judge how local the hub-and-spoke comparison is.
    hub_diagnostics = {
        'hub_seed': hub_seed,
        'hub_elapsed_s': hub_elapsed,
        'hub_steps': L_HUB,
        'hub_accepted_moves': accepted_moves,
        'hub_accept_fraction': accept_frac,
        'revrecom_M_bound_hit_rate': reverr_rate,
        'frac_precincts_moved_enacted_to_hub': (
            sum(1 for n in hub_assignment
                if hub_assignment[n] != ENACTED_ASSIGNMENT[n]) / len(hub_assignment)
            if ENACTED_ASSIGNMENT else float('nan')
        ),
    }
    if accept_frac < 0.02:
        print("  WARNING: very low accepted-move fraction. Spokes may barely "
              "leave the hub, weakening power. Consider raising REVRECOM_M "
              "and/or L_WALK (keep them fixed for the production run) -- this "
              "does not affect validity, only power.")
    return hub_assignment, hub_diagnostics


# ============================================================
# STEP 3 — Spoke chains
# ============================================================


def _spoke_worker(args):
    """
    Worker for a single spoke.
    args = (spoke_index, hub_assignment, seed)
    Returns (row_dict, assignment_dict) where row_dict is the score row
    and assignment_dict maps node_id -> 0-indexed district label.
    """
    spoke_idx, hub_assignment, seed = args
    endpoint_assignment = _run_chain_get_endpoint(hub_assignment, L_SPOKE, seed)
    my_updaters         = _build_updaters()
    endpoint_partition  = GeographicPartition(graph=graph,
                                              assignment=endpoint_assignment,
                                              updaters=my_updaters)
    scores = _functional_score_from_partition(endpoint_partition)

    # GeoSim revision: locality diagnostics. `frac_moved_vs_hub` and
    # `frac_moved_vs_enacted` are the fraction of precincts whose district
    # label differs between this spoke and the hub / the enacted plan. They
    # quantify how far L_SPOKE steps actually carry a plan, which is what the
    # chain length k controls (power, not validity). cut_edges and
    # county_splits are recorded so constraint tightening can be examined
    # post hoc and so the compactness of the simulated ensemble can be
    # compared to the enacted plan.
    n_prec = len(endpoint_assignment)
    moved_hub = sum(1 for n in endpoint_assignment
                    if endpoint_assignment[n] != hub_assignment[n])
    moved_enacted = (
        sum(1 for n in endpoint_assignment
            if endpoint_assignment[n] != ENACTED_ASSIGNMENT[n]) / n_prec
        if ENACTED_ASSIGNMENT else float('nan')
    )
    diagnostics = {
        'frac_moved_vs_hub': moved_hub / n_prec,
        'frac_moved_vs_enacted': moved_enacted,
        'cut_edges': len(endpoint_partition["cut_edges"]),
        'county_splits': endpoint_partition["county_splits"]["count"],
        'seed': seed,
    }
    return {'spoke': spoke_idx, **scores, **diagnostics}, endpoint_assignment


def run_spokes(hub_assignment):
    """
    Spawn M_SPOKES independent chains from hub, each of length L_SPOKE.
    Returns (DataFrame of scores, dict mapping spoke_idx -> assignment dict).
    """
    print(f"\n=== Running {M_SPOKES} spokes "
          f"(L={L_SPOKE} steps each, {N_WORKERS} workers) ===")
    t0    = time.time()
    seeds = [stdlib_random.randint(0, 10**9) for _ in range(M_SPOKES)]
    args  = [(i, hub_assignment, seeds[i]) for i in range(M_SPOKES)]
    rows  = []
    spoke_assignments = {}

    if N_WORKERS > 1:
        with mp.Pool(processes=N_WORKERS) as pool:
            for i, (row, assignment) in enumerate(
                    pool.imap_unordered(_spoke_worker, args)):
                rows.append(row)
                spoke_assignments[row['spoke']] = assignment
                if (i + 1) % 10 == 0:
                    print(f"  {i+1}/{M_SPOKES} spokes done "
                          f"({time.time()-t0:.0f}s elapsed)")
    else:
        for i, arg in enumerate(args):
            row, assignment = _spoke_worker(arg)
            rows.append(row)
            spoke_assignments[row['spoke']] = assignment
            if (i + 1) % 10 == 0:
                print(f"  {i+1}/{M_SPOKES} spokes done "
                      f"({time.time()-t0:.0f}s elapsed)")

    print(f"  All spokes complete in {time.time()-t0:.1f}s.")
    return pd.DataFrame(rows), spoke_assignments


# ============================================================
# STEP 4 — Exact Besag-Clifford p-values
# ============================================================



def compute_bc_pvalues(enacted_scores, spoke_df):
    """
    Rank enacted map among spoke endpoints.

    Primary lower-tail tests use F_B, F_L, and F_joint because these
    are demographically centered versions of the axiom-derived O scores.

    O_B, O_L, and O_joint are also reported, along with ensemble-standardized
    Z scores:
        Z = (O_enacted - mean(O_spokes)) / sd(O_spokes)
    """
    M = len(spoke_df)

    def _pval(enacted_val, col):
        vals   = spoke_df[col].dropna()
        n_leq  = (vals <= enacted_val).sum()
        n_geq  = (vals >= enacted_val).sum()
        p_low  = (n_leq + 1) / (len(vals) + 1)
        p_high = (n_geq + 1) / (len(vals) + 1)
        rank   = int(n_leq) + 1
        return p_low, p_high, rank

    def _z(enacted_val, col):
        sd = spoke_df[col].std()
        if pd.isna(sd) or sd == 0:
            return float('nan')
        return float((enacted_val - spoke_df[col].mean()) / sd)

    results = {
        'mode': MODEL_MODE, 'L_hub': L_HUB, 'L_spoke': L_SPOKE,
        'M_spokes': M, 'cutoff': EFFECTIVENESS_CUTOFF,
        'm_bar_B': M_BAR_B, 'm_bar_L': M_BAR_L,
        'prop_seats_B':    NUM_DISTRICTS * M_BAR_B,
        'prop_seats_L':    NUM_DISTRICTS * M_BAR_L,
    }

    for col in ['O_B', 'O_L', 'F_B', 'F_L']:
        results[f'enacted_{col}'] = enacted_scores[col]
        results[f'mean_{col}']    = spoke_df[col].mean()
        results[f'median_{col}']  = spoke_df[col].median()
        results[f'sd_{col}']      = spoke_df[col].std()
        results[f'p5_{col}']      = spoke_df[col].quantile(0.05)
        results[f'p95_{col}']     = spoke_df[col].quantile(0.95)

    # Ensemble-frontier standardized scores using the canonical O(pi)
    for col in ['O_B', 'O_L']:
        results[f'Z_{col}'] = _z(enacted_scores[col], col)

    # Primary B-C exact p-values on calibrated F(pi)
    for label, col in [('B', 'F_B'), ('L', 'F_L')]:
        p_low, p_high, rank = _pval(enacted_scores[col], col)
        results[f'p_{label}_lower'] = p_low
        results[f'p_{label}_upper'] = p_high
        results[f'rank_{label}'] = rank

    # Secondary p-values on canonical O(pi), useful for transparency
    for label, col in [('O_B', 'O_B'), ('O_L', 'O_L')]:
        p_low, p_high, rank = _pval(enacted_scores[col], col)
        results[f'p_{label}_lower'] = p_low
        results[f'p_{label}_upper'] = p_high
        results[f'rank_{label}'] = rank

    return results


# ============================================================
# OUTPUT — Console
# ============================================================



def print_results(results, spoke_df):
    M   = results['M_spokes']
    sig = lambda p: ' *** SIGNIFICANT' if p < 0.05 else (' * marginal' if p < 0.10 else '')

    print("\n" + "=" * 72)
    print("AXIOM-DERIVED MINORITY OPPORTUNITY FUNCTIONAL")
    print("WITH DIVERSITY CALIBRATION AND BESAG-CLIFFORD EXACT TEST")
    print("=" * 72)
    print(f"Model mode           : {results['mode']}")
    print(f"Hub length (L)       : {results['L_hub']}")
    print(f"Spoke length (L)     : {results['L_spoke']}")
    print(f"Num spokes (M)       : {M}")
    print(f"Effectiveness cutoff : {results['cutoff']}  (legacy comparison only)")
    print()

    print("Canonical opportunity scores O(pi): expected opportunity districts")
    for label, col in [
        ("Black", "O_B"),
        ("Latino", "O_L"),
    ]:
        print(f"  {label}:")
        print(f"    Enacted O value      : {results[f'enacted_{col}']:.4f}")
        print(f"    Null mean +/- SD     : {results[f'mean_{col}']:.4f} +/- "
              f"{results[f'sd_{col}']:.4f}")
        print(f"    Ensemble Z score     : {results[f'Z_{col}']:+.3f}")
        print(f"    O lower-tail p-value : {results[f'p_{col}_lower']:.4f}")

    print()
    print("Primary calibrated opportunity gaps F(pi) = O(pi) - K*m_bar")
    print("Lower-tail p-values test unusually low opportunity relative to")
    print("the demographic baseline and the Besag-Clifford spoke null.")
    print()

    for label, col, pkey, rkey in [
        ("Black",     'F_B',     'p_B_lower',     'rank_B'),
        ("Latino",    'F_L',     'p_L_lower',     'rank_L'),
    ]:
        print(f"  {label} calibrated functional:")
        print(f"    Enacted F value    : {results[f'enacted_{col}']:+.4f} districts")
        print(f"    Null mean +/- SD   : {results[f'mean_{col}']:+.4f} +/- "
              f"{results[f'sd_{col}']:.4f}")
        print(f"    5th--95th pct.     : [{results[f'p5_{col}']:+.3f}, "
              f"{results[f'p95_{col}']:+.3f}]")
        print(f"    Rank (of {M+1})    : {results[rkey]}")
        print(f"    p-value (lower <-) : {results[pkey]:.4f}{sig(results[pkey])}")
        print()

    print("Interpretation:")
    print("  O(pi) is the axiom-derived expected number of opportunity districts.")
    print("  F(pi) is the legally interpretable, diversity-calibrated gap.")
    print("  Z compares the enacted plan to the state-specific opportunity frontier.")
    print("  Small lower-tail B-C p-values indicate unusually low minority opportunity.")
    print("=" * 72)


# ============================================================
# OUTPUT — Distribution Plots
# ============================================================



def save_distribution_plots(enacted_scores, spoke_df, run_name):
    """
    Save two figures:
      1. Canonical O(pi) null distributions.
      2. Calibrated F(pi) null distributions.

    The F(pi) figure is the primary testing figure.
    """
    def _plot(title, base_suffix, formulas):
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))
        fig.suptitle(title, fontsize=12, fontweight='bold')

        for ax, (col, label, formula) in zip(axes, formulas):
            vals = spoke_df[col].dropna()
            enacted_val = enacted_scores[col]

            ax.hist(vals, bins=30, alpha=0.65,
                    edgecolor='white', linewidth=0.5,
                    label='Spoke null distribution')
            ax.axvline(enacted_val, linewidth=2.0, linestyle='-',
                       label=f'Enacted ({enacted_val:+.3f})')

            if col.startswith('F_'):
                ax.axvline(0, color='black', linewidth=1.2, linestyle='--',
                           label='Demographic baseline (F=0)')

            n_leq = (vals <= enacted_val).sum()
            p_val = (n_leq + 1) / (len(vals) + 1)
            ax.text(0.03, 0.97, f'p = {p_val:.4f}',
                    transform=ax.transAxes, va='top', ha='left',
                    fontsize=10, fontweight='bold')

            ax.set_xlabel('Score value (districts)', fontsize=10)
            ax.set_ylabel('Count' if ax is axes[0] else '', fontsize=10)
            ax.set_title(f'{label}\n{formula}', fontsize=9)
            ax.legend(fontsize=7, loc='upper right')
            ax.spines['top'].set_visible(False)
            ax.spines['right'].set_visible(False)

        plt.tight_layout()
        base = DIR + f'outputs/{base_suffix}_{run_name}'
        plt.savefig(base + '.pdf', bbox_inches='tight', dpi=300)
        plt.savefig(base + '.png', bbox_inches='tight', dpi=150)
        plt.close()
        print(f"Distribution plots saved:")
        print(f"  {base}.pdf")
        print(f"  {base}.png")
        return base + '.pdf'

    o_pdf = _plot(
        'Besag-Clifford Null Distribution -- Canonical Opportunity Scores O(pi)',
        'bc_canonical_O_distributions',
        [
            ('O_B',     'Black',     r'$O_B(\pi)=\sum_d p_d^B$'),
            ('O_L',     'Latino',    r'$O_L(\pi)=\sum_d p_d^L$'),
        ]
    )

    f_pdf = _plot(
        'Besag-Clifford Null Distribution -- Calibrated Opportunity Gaps F(pi)',
        'bc_calibrated_F_distributions',
        [
            ('F_B',     'Black',     r'$F_B(\pi)=O_B(\pi)-K\bar{m}_B$'),
            ('F_L',     'Latino',    r'$F_L(\pi)=O_L(\pi)-K\bar{m}_L$'),
        ]
    )

    return o_pdf, f_pdf


# ============================================================
# OUTPUT — LaTeX Table
# ============================================================


def save_latex_table(results, run_name):
    """
    Write a publication-ready LaTeX table.

    Include in paper with:
        \\input{outputs/bc_functional_table_<run_name>.tex}

    Requires: \\usepackage{booktabs}
    """
    def stars(p):
        if p < 0.01: return r'$^{***}$'
        if p < 0.05: return r'$^{**}$'
        if p < 0.10: return r'$^{*}$'
        return ''

    M  = results['M_spokes']
    pB = results['p_B_lower']
    pL = results['p_L_lower']

    lines = [
        r'% Auto-generated by besag_clifford_vra_functional.py',
        r'% Requires: \usepackage{booktabs}',
        r'\begin{table}[htbp]',
        r'\centering',
        (r'\caption{Diversity-Calibrated Minority Opportunity Functional: '
         r'Besag-Clifford Exact Significance Test (Texas HB4). '
         r'$F_g(\pi)=\sum_d p_d^g(\pi)-K\bar{m}_g$ measures the gap between '
         r'realized minority electoral opportunity and the De~Grandy proportional '
         r'baseline. $p_d^g(\pi)$ is the logit-model probability that group $g$\textquoteright s '
         r'preferred candidate wins district $d$ under plan $\pi$, estimated using '
         r'statewide ecological inference weights and recency-discounted election history. '
         r'$p$-values are exactly valid by \citet{besagclifford1989}, Proposition~3.3, '
         r'regardless of ReCom mixing time.}'),
        r'\label{tab:bc_functional}',
        r'\begin{tabular}{lcc}',
        r'\toprule',
        (r'& \textbf{Black} $F_B$ '
         r'& \textbf{Latino} $F_L$ \\'),
        r'\midrule',
        r'\multicolumn{3}{l}{\textit{Statewide proportional baseline}} \\',
        (f"Statewide CVAP fraction $\\bar{{m}}_g$ "
         f"& {results['m_bar_B']:.4f} "
         f"& {results['m_bar_L']:.4f} \\\\"),
        (f"Proportional seat target $K\\bar{{m}}_g$ "
         f"& {results['prop_seats_B']:.2f} "
         f"& {results['prop_seats_L']:.2f} \\\\"),
        r'\midrule',
        r'\multicolumn{3}{l}{\textit{Enacted map}} \\',
        (f"$F_g(\\pi_{{\\rm enacted}})$ "
         f"& {results['enacted_F_B']:+.4f} "
         f"& {results['enacted_F_L']:+.4f} \\\\"),
        r'\midrule',
        (r'\multicolumn{3}{l}{\textit{Null distribution '
         r'($M=' + str(M) + r'$ spokes, $L=' + str(L_SPOKE) + r'$ steps each)}} \\'),
        (f"Mean $\\bar{{F}}_g$ "
         f"& {results['mean_F_B']:+.4f} "
         f"& {results['mean_F_L']:+.4f} \\\\"),
        (f"Std.\\ dev.\\ "
         f"& {results['sd_F_B']:.4f} "
         f"& {results['sd_F_L']:.4f} \\\\"),
        (f"5th--95th pct.\\ "
         f"& [{results['p5_F_B']:+.3f}, {results['p95_F_B']:+.3f}] "
         f"& [{results['p5_F_L']:+.3f}, {results['p95_F_L']:+.3f}] \\\\"),
        (f"Rank of enacted (of $M+1={M+1}$) "
         f"& {results['rank_B']} "
         f"& {results['rank_L']} \\\\"),
        r'\midrule',
        r'\multicolumn{3}{l}{\textit{Besag-Clifford exact $p$-values}} \\',
        (f"Lower-tail $p$ (dilution direction) "
         f"& {pB:.4f}{stars(pB)} "
         f"& {pL:.4f}{stars(pL)} \\\\"),
        (f"Upper-tail $p$ "
         f"& {results['p_B_upper']:.4f} "
         f"& {results['p_L_upper']:.4f} \\\\"),
        r'\bottomrule',
        r'\multicolumn{3}{p{0.95\linewidth}}{\footnotesize',
        r'\textit{Notes:} Lower-tail $p$-values test whether the enacted map provides',
        r'unusually \emph{few} minority opportunity seats relative to the null distribution',
        r'of randomly drawn alternative plans (the vote dilution direction).',
        r'$p$-values are exactly valid regardless of Markov chain mixing time',
        r'\citep{besagclifford1989}.',
        r'Significance: $^{*}p<0.10$, $^{**}p<0.05$, $^{***}p<0.01$ (lower-tail, one-sided).',
        f'Model mode: {results["mode"]}. Hub length $L_{{\\rm hub}}={L_HUB}$.',
        r'The proportional baseline $K\bar{m}_g$ is the De~Grandy relevant fact',
        r'\citep[512 U.S.\ 997]{degrandy1994}: proportionality is not dispositive but',
        r'is evidence in the totality of circumstances.',
        r'} \\',
        r'\end{tabular}',
        r'\end{table}',
    ]

    path = DIR + f'outputs/bc_functional_table_{run_name}.tex'
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"LaTeX table saved: {path}")
    return path


# ============================================================
# MAIN
# ============================================================


def main():
    total_start = time.time()
    master_seed = (MASTER_SEED if MASTER_SEED >= 0
                   else stdlib_random.randint(0, 10**9))
    stdlib_random.seed(master_seed)
    print(f"Master seed: {master_seed} "
          f"({'from BC_SEED' if MASTER_SEED >= 0 else 'drawn at random'})")
    print(f"Run config: RUN_NAME={RUN_NAME}, L_WALK={L_WALK}, "
          f"M_SPOKES={M_SPOKES}, REVRECOM_M={REVRECOM_M}, "
          f"START_MAP={START_MAP}, MODEL_MODE={MODEL_MODE}")

    # 1. Score enacted map
    enacted_scores, enacted_partition = score_enacted_map()

    # Capture the enacted plan's cut-edges count so the compactness
    # constraint in _build_proposal_and_constraint can reference it. Workers
    # spawned later via fork() will inherit the populated value.
    global ENACTED_CUT_EDGES
    global COMPACTNESS_SLACK, COUNTY_SPLITS_SLACK  # read-only here, declared
    # global so editing these module constants (including to None) is always
    # picked up correctly inside main().
    ENACTED_CUT_EDGES = len(enacted_partition["cut_edges"])
    global ENACTED_ASSIGNMENT
    ENACTED_ASSIGNMENT = dict(enacted_partition.assignment)
    if COMPACTNESS_SLACK is not None:
        print(f"\n  Enacted cut-edges: {ENACTED_CUT_EDGES}")
        print(f"  Compactness threshold (cut-edges <= {COMPACTNESS_SLACK} x enacted): "
              f"{int(COMPACTNESS_SLACK * ENACTED_CUT_EDGES)}")
    else:
        print("\n  Compactness constraint disabled (COMPACTNESS_SLACK = None).")

    # Same for the county-splits count: compute from the enacted partition
    # once, store as a module global so worker processes inherit it via
    # fork(). Done after the cut-edges capture so the diagnostics print in a
    # logical order at startup.
    global ENACTED_COUNTY_SPLITS
    ENACTED_COUNTY_SPLITS = _count_county_splits(enacted_partition)
    if COUNTY_SPLITS_SLACK is not None:
        print(f"  Enacted county splits: {ENACTED_COUNTY_SPLITS}")
        print(f"  County-splits threshold (splits <= {COUNTY_SPLITS_SLACK} x enacted): "
              f"{int(COUNTY_SPLITS_SLACK * ENACTED_COUNTY_SPLITS)}")
    else:
        print("  County-splits constraint disabled (COUNTY_SPLITS_SLACK = None).")

    # 2. Hub chain
    hub_assignment, hub_diagnostics = run_hub_chain(enacted_partition)

    # 3. Spoke chains
    spoke_df, spoke_assignments = run_spokes(hub_assignment)

    # 4. B-C p-values and ensemble-standardized Z scores
    results = compute_bc_pvalues(enacted_scores, spoke_df)

    # 5. Console output
    print_results(results, spoke_df)

    # 6. CSVs
    spoke_path = DIR + f'outputs/bc_opportunity_spokes_{RUN_NAME}.csv'
    pval_path  = DIR + f'outputs/bc_opportunity_results_{RUN_NAME}.csv'
    spoke_df.to_csv(spoke_path, index=False)
    pd.DataFrame([results]).to_csv(pval_path, index=False)
    print(f"\nSpoke scores saved : {spoke_path}")
    print(f"Results saved      : {pval_path}")

    # 6b. Save spoke assignment plans + enacted assignment as a single
    # parquet for downstream visualization / analysis. Each column is one
    # plan; rows are precincts indexed by GEO_ID. The 'enacted' column holds
    # the 0-indexed remap of the enacted plan (so it shares the label space
    # with spokes; real CD k corresponds to internal_idx k-1, matching the
    # remap in score_enacted_map()).
    #
    # Build all columns at once via a dict + single DataFrame construction
    # rather than inserting columns in a loop -- the loop form fragments the
    # frame and floods the log with pandas PerformanceWarnings at M=200.
    nodes_order = list(graph.nodes())
    enacted_assignment = dict(enacted_partition.assignment)
    plan_columns = {
        "enacted": [enacted_assignment[n] for n in nodes_order],
        # GeoSim revision: the hub is saved too. Without it the realized
        # geometry of the hub-and-spoke construction cannot be reconstructed
        # from the artifact, and spoke-to-hub distances cannot be recomputed.
        "hub": [hub_assignment[n] for n in nodes_order],
    }
    for spoke_idx, assignment in sorted(spoke_assignments.items()):
        plan_columns[f"spoke_{spoke_idx:03d}"] = [assignment[n] for n in nodes_order]
    plans_df = pd.DataFrame(plan_columns, index=list(state_gdf[GEO_ID]))
    plans_df.index.name = GEO_ID
    plans_path = DIR + f'outputs/bc_plan_assignments_{RUN_NAME}.parquet'
    plans_df.to_parquet(plans_path)
    n_plans = len(plans_df.columns)
    print(f"Plan assignments saved: {plans_path} "
          f"({n_plans} plans x {len(plans_df)} precincts)")

    # 7. Distribution plots (PDF + PNG)
    save_distribution_plots(enacted_scores, spoke_df, RUN_NAME)

    # 8. LaTeX table
    save_latex_table(results, RUN_NAME)

    # 9. GeoSim revision: run-configuration record. Reviewer 2's principal
    # objection to the submitted version was that the hub/spoke chain length
    # was never reported; this file makes every simulation parameter, the
    # realized acceptance behaviour of the kernel, and the runtime part of the
    # reproducibility artifact for every run.
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL, text=True).strip()
    except Exception:
        commit = None
    run_config = {
        'run_name': RUN_NAME,
        'master_seed': master_seed,
        'k_walk_steps': L_WALK,
        'L_hub': L_HUB,
        'L_spoke': L_SPOKE,
        'M_spokes': M_SPOKES,
        'revrecom_M': REVRECOM_M,
        'model_mode': MODEL_MODE,
        'start_map': START_MAP,
        'num_districts': NUM_DISTRICTS,
        'pop_tol': POP_TOL,
        'compactness_slack': COMPACTNESS_SLACK,
        'county_splits_slack': COUNTY_SPLITS_SLACK,
        'enacted_cut_edges': ENACTED_CUT_EDGES,
        'enacted_county_splits': ENACTED_COUNTY_SPLITS,
        'effectiveness_cutoff_legacy': EFFECTIVENESS_CUTOFF,
        'n_workers': N_WORKERS,
        'graph_vertices': graph.number_of_nodes(),
        'graph_edges': graph.number_of_edges(),
        'python': platform.python_version(),
        'platform': platform.platform(),
        'git_commit': commit,
        'total_runtime_min': (time.time() - total_start) / 60.0,
        **hub_diagnostics,
        'spoke_frac_moved_vs_hub_mean': float(
            spoke_df['frac_moved_vs_hub'].mean())
        if 'frac_moved_vs_hub' in spoke_df else None,
        'spoke_frac_moved_vs_enacted_mean': float(
            spoke_df['frac_moved_vs_enacted'].mean())
        if 'frac_moved_vs_enacted' in spoke_df else None,
    }
    cfg_path = DIR + f'outputs/bc_run_config_{RUN_NAME}.json'
    with open(cfg_path, 'w') as fh:
        _json.dump(run_config, fh, indent=2, default=str)
    print(f"Run config saved   : {cfg_path}")

    print(f"\nTotal elapsed: {(time.time()-total_start)/60:.1f} minutes")
    print(f"(L_hub={L_HUB}, L_spoke={L_SPOKE}, M_spokes={M_SPOKES}, "
          f"workers={N_WORKERS})")


if __name__ == "__main__":
    main()