# -*- coding: utf-8 -*-
"""
besag_clifford_vra_opportunity.py
==========================================

Axiom-Derived Minority Opportunity Functional
with Diversity Calibration and Besag-Clifford exact inference.

Conceptual structure
--------------------
This implementation separates the theoretical functional from the
calibration layer:

1. Canonical opportunity functional:

       O_g(pi) = sum_d p_d^g(pi)

   where p_d^g(pi) is the model-based probability that group g's
   preferred candidate wins district d under plan pi.

   This is the object justified by the axioms in the paper: anonymity,
   district additivity, monotonicity, and normalization. O_g(pi) is the
   expected number of opportunity districts.

2. Diversity-calibrated opportunity gap:

       F_g(pi) = O_g(pi) - K * m_bar_g

   where m_bar_g is the statewide CVAP share of group g. F_g(pi) is not
   a replacement for O_g(pi); it is a centered version of the canonical
   opportunity score.

3. Ensemble-standardized score:

       Z_g(pi_enacted) = (O_g(pi_enacted) - E_rho[O_g(pi)]) / sd_rho(O_g(pi))

   This calibrates the enacted plan to the state-specific opportunity
   frontier generated by the neutral ReCom ensemble.

4. Besag-Clifford exact lower-tail p-value:

       p = (# spokes with statistic <= enacted statistic + 1) / (M + 1)

   The primary test statistic is F_g, but O_g and Z_g are reported.
"""

import random as stdlib_random
import time
import os
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib
matplotlib.use('Agg')  # headless backend -- must precede pyplot import
import matplotlib.pyplot as plt
from functools import partial
import operator
import multiprocessing as mp

from texas_gerrymandering_hb4.config import (
    TX_ELECTIONS, CANDIDATE_RACE_PARTY, PREC_COUNT_QUANTS_INPUT,
    INGROUP_WEIGHT_CSV_FILE, DROPPED_ELECS, STATEWIDE_RXC_EI_PREFERENCES_INPUT,
    RECENCY_WEIGHTS, MEAN_PREC_VOTE_COUNTS_INPUT, PRECINCT_DATASET_PARQUET,
)

# NOTE: gerrychain.random was deprecated. Per gerrychain release notes, the
# library now hooks directly into Python's stdlib `random` module, so seeding
# the stdlib `random` (already imported above as stdlib_random) controls all
# gerrychain randomness. No separate gc_random import is needed.
from gerrychain import (
    Graph, MarkovChain, GeographicPartition,
    accept, constraints, updaters, Election
)
from gerrychain.proposals import recom
from gerrychain.updaters import cut_edges, Tally
from gerrychain.tree import recursive_tree_part

from run_functions import (
    compute_final_dist, compute_W2, prob_conf_conversion,
    cand_pref_outcome_sum, cand_pref_all_draws_outcomes,
    precompute_state_weights, compute_district_weights
)

# ============================================================
# USER PARAMETERS  (identical to besag_clifford_vra.py)
# ============================================================

L_HUB     = 500
L_SPOKE   = 500
M_SPOKES  = 200
N_WORKERS = max(1, mp.cpu_count() - 1)

START_MAP  = 'CD'
RUN_NAME   = 'TX_BC_functional'
MODEL_MODE = 'statewide'

EFFECTIVENESS_CUTOFF = 0.6  # kept for legacy comparison columns only

# ============================================================
# FIXED PARAMETERS
# ============================================================

NUM_DISTRICTS   = 38
POP_TOL         = 0.01
PLOT_PATH       = PRECINCT_DATASET_PARQUET
DIR             = ''

TOT_POP         = 'TOTALPOP'
CVAP            = 'CVAP'
WCVAP           = 'WCVAP'
HCVAP           = 'HCVAP'
BCVAP           = 'BCVAP'
GEO_ID          = 'CNTYVTD'
C_X             = 'C_X'
C_Y             = 'C_Y'

if not os.path.exists(DIR + 'outputs'):
    os.mkdir(DIR + 'outputs')

# ============================================================
# DATA LOADING  (identical to besag_clifford_vra.py)
# ============================================================

print("Loading data...")

elec_data        = pd.read_csv(TX_ELECTIONS)
dropped_elecs    = pd.read_csv(DROPPED_ELECS)["Dropped Elections"]
recency_weights  = pd.read_csv(RECENCY_WEIGHTS)
min_cand_weights = pd.read_csv(INGROUP_WEIGHT_CSV_FILE)
cand_race_table  = pd.read_csv(CANDIDATE_RACE_PARTY)
EI_statewide     = pd.read_csv(STATEWIDE_RXC_EI_PREFERENCES_INPUT)
prec_ei_df       = pd.read_csv(PREC_COUNT_QUANTS_INPUT,     dtype={GEO_ID: 'str'})
mean_prec_counts = pd.read_csv(MEAN_PREC_VOTE_COUNTS_INPUT, dtype={GEO_ID: 'str'})

# TX_logit_params.csv is optional; when absent we run compute_final_dist with
# logit=False so the unscaled VRA opportunity score is used directly.
_logit_params_path = os.path.join(DIR, 'TX_logit_params.csv')
if os.path.exists(_logit_params_path):
    logit_params = pd.read_csv(_logit_params_path)
    USE_LOGIT = True
else:
    print(f"  TX_logit_params.csv not found at '{_logit_params_path}'; "
          "running with logit=False.")
    logit_params = None
    USE_LOGIT = False

# ---- precinct dataset (geoparquet from data engineering layer) ----
state_gdf = gpd.read_parquet(PLOT_PATH)
state_gdf["CD"]   = state_gdf["CD"].astype('int')
state_gdf.columns = state_gdf.columns.str.replace("-", "_")

# ---- graph ----
graph = Graph.from_geodataframe(state_gdf)
graph.add_data(state_gdf)
centroids_geom = state_gdf.centroid
for node in graph.nodes():
    graph.nodes[node]["C_X"] = centroids_geom.x[node]
    graph.nodes[node]["C_Y"] = centroids_geom.y[node]

# ---- elections data structures ----
elecs_bool      = ~elec_data.Election.isin(list(dropped_elecs))
elec_data_trunc = elec_data[elecs_bool].reset_index(drop=True)
elec_sets       = list(set(elec_data_trunc["Election Set"]))
elections       = list(elec_data_trunc["Election"])
general_elecs   = list(elec_data_trunc[elec_data_trunc["Type"] == 'General'].Election)
primary_elecs   = list(elec_data_trunc[elec_data_trunc["Type"] == 'Primary'].Election)
runoff_elecs    = list(elec_data_trunc[elec_data_trunc["Type"] == 'Runoff'].Election)

elec_set_dict = {}
for elec_set in elec_sets:
    sub = elec_data_trunc[elec_data_trunc["Election Set"] == elec_set]
    elec_set_dict[elec_set] = dict(zip(sub.Type, sub.Election))

elec_match_dict = dict(zip(elec_data_trunc["Election"], elec_data_trunc["Election Set"]))

# ============================================================
# 2024 STATEWIDE ELECTION → CANDIDATE COLUMN MAPPING
# ============================================================
# The MGGG VRA_ensembles workflow this file was adapted from used candidate
# columns whose names embedded the full Election key as a substring (e.g.
# "ClintonD_16G_President" contains "16G_President"), so a substring match
# `elec in candidate_col` was enough to pull the right candidate set. The
# 2024 Texas dataset built by the data engineering and EI layers uses a
# different naming convention — candidate columns are
# "<Lastname><Party>_24G" / "_24P", with no embedded office — so we list
# the candidate columns per Election explicitly here. Keys must match the
# Election column in TX_elections.csv (and the keys in
# pipelines/ecological_inference_layer/run_ei.py::ELECTIONS).
ELECTION_CANDIDATES_2024 = {
    "24G_President":  ["TrumpR_24G",     "HarrisD_24G"],
    "24G_US_Sen":     ["CruzR_24G",      "AllredD_24G"],
    "24G_RR_Comm_1":  ["CraddickR_24G",  "CulbertD_24G"],
    "24P_PresD": [
        "BidenD_24P", "CornejoD_24P", "LockeD_24P", "LozadaD_24P",
        "PerezD_24P", "PhillipsD_24P", "UygurD_24P", "WilliamsonD_24P",
    ],
    "24P_PresR": [
        "BinkleyR_24P", "HaleyR_24P", "StuckenbergR_24P", "TrumpR_24P",
        "ChristieR_24P", "RamaswamyR_24P", "HutchinsonR_24P", "DeSantisR_24P",
    ],
    "24P_SenD": [
        "AllredD_24P", "GomezD_24P", "GonzalezD_24P", "GutierrezD_24P",
        "HassanD_24P", "KeoughD_24P", "PrillimanD_24P", "ShermanD_24P",
        "TchenkoD_24P",
    ],
    "24P_SenR":  ["CruzR_24P", "GibsonR_24P", "LopezR_24P"],
    "24P_RRCD":  ["BurchD_24P", "CulbertD_24P"],
    "24P_RRCR": [
        "ClarkR_24P", "CraddickR_24P", "HowellR_24P",
        "MatlockR_24P", "ReyesR_24P",
    ],
}

candidates = {}
for elec in elections:
    if elec not in ELECTION_CANDIDATES_2024:
        raise KeyError(
            f"Election {elec!r} from TX_elections.csv is not present in "
            f"ELECTION_CANDIDATES_2024. Add the candidate column list there "
            f"before running."
        )
    cands_list = [c for c in ELECTION_CANDIDATES_2024[elec]
                  if c in state_gdf.columns]
    missing = [c for c in ELECTION_CANDIDATES_2024[elec] if c not in state_gdf.columns]
    if missing:
        print(f"  WARNING: {elec}: candidate columns not in precinct dataset, "
              f"dropped: {missing}")
    if elec in general_elecs:
        cands_list = cands_list[:2]
    candidates[elec] = dict(zip(range(len(cands_list)), cands_list))

cand_race_dict        = cand_race_table.set_index("Candidates").to_dict()["Race"]
min_cand_weights_dict = {k: min_cand_weights.to_dict()[k][0]
                          for k in min_cand_weights.to_dict().keys()}

elec_years     = [elec_data_trunc.loc[elec_data_trunc["Election Set"] == es, 'Year']
                  .values[0].astype(str) for es in elec_sets]
recency_scores = [recency_weights[yr][0] for yr in elec_years]
recency_W1     = np.tile(recency_scores, (NUM_DISTRICTS, 1)).transpose()

(black_weight_state,  hisp_weight_state,  neither_weight_state,
 black_weight_equal,  hisp_weight_equal,  neither_weight_equal,
 black_pref_cands_prim_state,   hisp_pref_cands_prim_state,
 black_pref_cands_runoffs_state, hisp_pref_cands_runoffs_state) = \
    precompute_state_weights(
        NUM_DISTRICTS, elec_sets, elec_set_dict, recency_W1, EI_statewide,
        primary_elecs, runoff_elecs, elec_match_dict,
        min_cand_weights_dict, cand_race_dict
    )

demogs    = ['BCVAP', 'HCVAP']
bases     = {col.split('.')[0] + '.' + col.split('.')[1]
             for col in prec_ei_df.columns
             if col[:5] in demogs and 'abstain' not in col
             and not any(x in col for x in general_elecs)}
base_dict = {b: (b.split('.')[0].split('_')[0],
                 '_'.join(b.split('.')[1].split('_')[1:-1]))
             for b in bases}
outcomes = {val: [] for val in base_dict.values()}
for b in bases:
    outcomes[base_dict[b]].append(b)

precs               = list(state_gdf[GEO_ID])
prec_draws_outcomes = cand_pref_all_draws_outcomes(prec_ei_df, precs, bases, outcomes)

print("Data loaded.")

# ============================================================
# STATEWIDE DEMOGRAPHIC FRACTIONS  (new)
# ============================================================

def _compute_statewide_fractions(gdf):
    """
    Compute statewide minority CVAP fractions from the shapefile.

    Called once at module load. Results stored as module-level
    constants M_BAR_B, M_BAR_L, M_BAR_COMBINED.

    Returns
    -------
    m_bar_B        : float  Black CVAP / Total CVAP
    m_bar_L        : float  Latino CVAP / Total CVAP
    m_bar_combined : float  (Black + Latino) CVAP / Total CVAP
    """
    total_cvap    = gdf[CVAP].sum()
    black_cvap    = gdf[BCVAP].sum()
    hisp_cvap     = gdf[HCVAP].sum()
    combined_cvap = black_cvap + hisp_cvap

    m_bar_B        = black_cvap    / total_cvap
    m_bar_L        = hisp_cvap     / total_cvap
    m_bar_combined = combined_cvap  / total_cvap

    print(f"\nStatewide CVAP fractions:")
    print(f"  m_bar_B        = {m_bar_B:.4f}  ({100*m_bar_B:.2f}%)")
    print(f"  m_bar_L        = {m_bar_L:.4f}  ({100*m_bar_L:.2f}%)")
    print(f"  m_bar_combined = {m_bar_combined:.4f}  ({100*m_bar_combined:.2f}%)")
    print(f"  Proportional seat targets:")
    print(f"    Black    : {NUM_DISTRICTS * m_bar_B:.2f}")
    print(f"    Latino   : {NUM_DISTRICTS * m_bar_L:.2f}")
    print(f"    Combined : {NUM_DISTRICTS * m_bar_combined:.2f}")

    return m_bar_B, m_bar_L, m_bar_combined


M_BAR_B, M_BAR_L, M_BAR_COMBINED = _compute_statewide_fractions(state_gdf)

# ============================================================
# UPDATERS  (identical to besag_clifford_vra.py)
# ============================================================

def final_elec_model(partition):
    """
    Elections model updater. Identical to besag_clifford_vra.py.

    Computes per-district win probabilities for minority-preferred
    candidates under statewide, equal, and district EI modes.

    Returns
    -------
    (final_state_prob, final_equal_prob, final_dist_prob)
    Each: {district_index: (hisp_prob, black_prob, neither_prob, combined_prob)}
    """
    if partition.parent is not None:
        dict1 = dict(partition.parent.assignment)
        dict2 = dict(partition.assignment)
        differences = (
            set([dict1[k] for k in dict1 if dict1[k] != dict2[k]]) |
            set([dict2[k] for k in dict2 if dict1[k] != dict2[k]])
        )
        dist_changes = sorted(differences)
    else:
        dist_changes = range(NUM_DISTRICTS)

    order = [x for x in partition.parts]

    dist_elec_results = {}
    for elec in elections:
        cands = candidates[elec]
        outcome_list = [dict(zip(order, partition[elec].percents(cand)))
                        for cand in cands.keys()]
        dist_elec_results[elec] = {
            d: {cands[i]: outcome_list[i][d] for i in cands.keys()}
            for d in range(NUM_DISTRICTS)
        }

    map_winners = pd.DataFrame(columns=dist_changes)
    map_winners["Election"]      = elections
    map_winners["Election Set"]  = elec_data_trunc["Election Set"]
    map_winners["Election Type"] = elec_data_trunc["Type"]
    for i in dist_changes:
        map_winners[i] = [
            max(dist_elec_results[elec][i].items(), key=operator.itemgetter(1))[0]
            for elec in elections
        ]

    # statewide mode
    final_state_prob_dict = compute_final_dist(
        map_winners, black_pref_cands_prim_state, black_pref_cands_runoffs_state,
        hisp_pref_cands_prim_state, hisp_pref_cands_runoffs_state,
        neither_weight_state, black_weight_state, hisp_weight_state,
        dist_elec_results, dist_changes, cand_race_table, NUM_DISTRICTS,
        candidates, elec_sets, elec_set_dict, "statewide", partition,
        logit_params, logit=USE_LOGIT
    )

    # equal mode
    final_equal_prob_dict = compute_final_dist(
        map_winners, black_pref_cands_prim_state, black_pref_cands_runoffs_state,
        hisp_pref_cands_prim_state, hisp_pref_cands_runoffs_state,
        neither_weight_equal, black_weight_equal, hisp_weight_equal,
        dist_elec_results, dist_changes, cand_race_table, NUM_DISTRICTS,
        candidates, elec_sets, elec_set_dict, "equal", partition,
        logit_params, logit=USE_LOGIT
    )

    # district mode
    (black_weight_dist,  hisp_weight_dist,  neither_weight_dist,
     black_pref_cands_prim_dist,   black_pref_cands_runoffs_dist,
     hisp_pref_cands_prim_dist,    hisp_pref_cands_runoffs_dist) = \
        compute_district_weights(
            dist_changes, elec_sets, elec_set_dict, state_gdf, partition,
            prec_draws_outcomes, GEO_ID, primary_elecs, runoff_elecs,
            elec_match_dict, bases, outcomes, recency_W1,
            cand_race_dict, min_cand_weights_dict
        )

    final_dist_prob_dict = compute_final_dist(
        map_winners, black_pref_cands_prim_dist, black_pref_cands_runoffs_dist,
        hisp_pref_cands_prim_dist, hisp_pref_cands_runoffs_dist,
        neither_weight_dist, black_weight_dist, hisp_weight_dist,
        dist_elec_results, dist_changes, cand_race_table, NUM_DISTRICTS,
        candidates, elec_sets, elec_set_dict, 'district', partition,
        logit_params, logit=USE_LOGIT
    )

    if partition.parent is None:
        final_state_prob = {k: final_state_prob_dict[k] for k in sorted(final_state_prob_dict)}
        final_equal_prob = {k: final_equal_prob_dict[k] for k in sorted(final_equal_prob_dict)}
        final_dist_prob  = {k: final_dist_prob_dict[k]  for k in sorted(final_dist_prob_dict)}
    else:
        final_state_prob = partition.parent["final_elec_model"][0].copy()
        final_equal_prob = partition.parent["final_elec_model"][1].copy()
        final_dist_prob  = partition.parent["final_elec_model"][2].copy()
        for i in dist_changes:
            final_state_prob[i] = final_state_prob_dict[i]
            final_equal_prob[i] = final_equal_prob_dict[i]
            final_dist_prob[i]  = final_dist_prob_dict[i]

    return final_state_prob, final_equal_prob, final_dist_prob



# ============================================================
# AXIOM-DERIVED AND CALIBRATED OPPORTUNITY FUNCTIONALS
# ============================================================

def compute_opportunity_scores(prob_dict,
                               m_bar_B, m_bar_L, m_bar_combined,
                               K=NUM_DISTRICTS):
    """
    Compute both the canonical opportunity functional O(pi) and
    its diversity-calibrated version F(pi).

    Canonical functional, justified by the axioms in the paper:
        O_g(pi) = sum_d p_d^g(pi)

    Diversity-calibrated gap:
        F_g(pi) = O_g(pi) - K * m_bar_g

    Coalition version:
        O_joint(pi) = sum_d max(p_d^B(pi), p_d^L(pi))
        F_joint(pi) = O_joint(pi) - K * m_bar_combined
    """
    if "N/A" in prob_dict.values():
        return {
            'O_B': float('nan'), 'O_L': float('nan'), 'O_joint': float('nan'),
            'F_B': float('nan'), 'F_L': float('nan'), 'F_joint': float('nan'),
            'baseline_B': K * m_bar_B,
            'baseline_L': K * m_bar_L,
            'baseline_joint': K * m_bar_combined,
        }

    p_B_list, p_L_list = [], []
    for d in sorted(prob_dict.keys()):
        hisp_prob, black_prob, neither_prob, combined_prob = prob_dict[d]
        p_L_list.append(hisp_prob)
        p_B_list.append(black_prob)

    p_B_arr = np.array(p_B_list, dtype=float)
    p_L_arr = np.array(p_L_list, dtype=float)

    O_B = float(p_B_arr.sum())
    O_L = float(p_L_arr.sum())
    O_joint = float(np.maximum(p_B_arr, p_L_arr).sum())

    baseline_B = float(K * m_bar_B)
    baseline_L = float(K * m_bar_L)
    baseline_joint = float(K * m_bar_combined)

    return {
        'O_B': O_B,
        'O_L': O_L,
        'O_joint': O_joint,
        'F_B': O_B - baseline_B,
        'F_L': O_L - baseline_L,
        'F_joint': O_joint - baseline_joint,
        'baseline_B': baseline_B,
        'baseline_L': baseline_L,
        'baseline_joint': baseline_joint,
    }


# Backwards-compatible alias. Existing calls will still work, but the new
# implementation should use compute_opportunity_scores() so O(pi) is retained.
def compute_opportunity_functional(prob_dict,
                                   m_bar_B, m_bar_L, m_bar_combined,
                                   K=NUM_DISTRICTS):
    scores = compute_opportunity_scores(
        prob_dict, m_bar_B, m_bar_L, m_bar_combined, K
    )
    return scores['F_B'], scores['F_L'], scores['F_joint']


def _functional_score_from_partition(partition):
    """
    Extract O_B, O_L, O_joint and F_B, F_L, F_joint from a partition.

    O(pi) is the axiom-derived theoretical functional.
    F(pi) is the diversity-calibrated score used for the primary
    lower-tail Besag-Clifford test.
    """
    final_state_prob, final_equal_prob, final_dist_prob = \
        partition["final_elec_model"]

    prob_dict = (final_state_prob if MODEL_MODE == 'statewide' else
                 final_equal_prob if MODEL_MODE == 'equal'     else
                 final_dist_prob)

    scores = compute_opportunity_scores(
        prob_dict, M_BAR_B, M_BAR_L, M_BAR_COMBINED
    )

    if "N/A" not in prob_dict.values():
        hisp_eff  = sum(1 for v in prob_dict.values()
                        if v[0] >= EFFECTIVENESS_CUTOFF)
        black_eff = sum(1 for v in prob_dict.values()
                        if v[1] >= EFFECTIVENESS_CUTOFF)
        distinct  = len(
            set(d for d, v in prob_dict.items() if v[0] >= EFFECTIVENESS_CUTOFF) |
            set(d for d, v in prob_dict.items() if v[1] >= EFFECTIVENESS_CUTOFF)
        )
    else:
        hisp_eff = black_eff = distinct = float('nan')

    return {
        **scores,
        'hisp_eff': hisp_eff,
        'black_eff': black_eff,
        'distinct_eff': distinct,
    }

# ============================================================
# CHAIN INFRASTRUCTURE  (identical to besag_clifford_vra.py)
# ============================================================

def _build_updaters():
    my_updaters = {
        "population": updaters.Tally(TOT_POP, alias="population"),
        "CVAP":       updaters.Tally(CVAP,    alias="CVAP"),
        "WCVAP":      updaters.Tally(WCVAP,   alias="WCVAP"),
        "HCVAP":      updaters.Tally(HCVAP,   alias="HCVAP"),
        "BCVAP":      updaters.Tally(BCVAP,   alias="BCVAP"),
        "Sum_CX":     updaters.Tally(C_X,     alias="Sum_CX"),
        "Sum_CY":     updaters.Tally(C_Y,     alias="Sum_CY"),
        "cut_edges":  cut_edges,
        "final_elec_model": final_elec_model,
    }
    # Benchmark general elections that exist in the 2024 schema. The original
    # 2012/2016/2018 benchmark candidates are not in the precinct dataset.
    benchmark = [
        Election("PRES24G", {"Democratic": 'HarrisD_24G',
                              "Republican": 'TrumpR_24G'},     alias="PRES24G"),
        Election("SEN24G",  {"Democratic": 'AllredD_24G',
                              "Republican": 'CruzR_24G'},      alias="SEN24G"),
        Election("RRC24G",  {"Democratic": 'CulbertD_24G',
                              "Republican": 'CraddickR_24G'},  alias="RRC24G"),
    ]
    my_updaters.update({e.name: e for e in benchmark})
    my_updaters.update({e.name: e for e in [Election(j, candidates[j]) for j in elections]})
    return my_updaters


def _build_proposal_and_constraint(initial_partition):
    total_pop = state_gdf[TOT_POP].sum()
    ideal_pop = total_pop / NUM_DISTRICTS
    proposal  = partial(recom, pop_col=TOT_POP, pop_target=ideal_pop,
                        epsilon=POP_TOL, node_repeats=3)
    pop_constraint = constraints.within_percent_of_ideal_population(
        initial_partition, POP_TOL
    )
    return proposal, pop_constraint


def _run_chain_get_endpoint(start_assignment, n_steps, seed):
    """Run ReCom for n_steps. Returns plain-dict assignment of final state."""
    stdlib_random.seed(seed)
    my_updaters = _build_updaters()
    init_part   = GeographicPartition(graph=graph,
                                      assignment=start_assignment,
                                      updaters=my_updaters)
    proposal, pop_constraint = _build_proposal_and_constraint(init_part)
    chain = MarkovChain(
        proposal=proposal,
        constraints=[pop_constraint],
        accept=accept.always_accept,
        initial_state=init_part,
        total_steps=n_steps,
    )
    endpoint = init_part
    for step in chain:
        endpoint = step
    return dict(endpoint.assignment)


# ============================================================
# STEP 1 — Score the enacted map
# ============================================================


def score_enacted_map():
    print("\n=== Scoring enacted map ===")
    total_pop = state_gdf[TOT_POP].sum()
    ideal_pop = total_pop / NUM_DISTRICTS

    if START_MAP == 'new_seed':
        assignment = recursive_tree_part(graph, range(NUM_DISTRICTS),
                                         ideal_pop, TOT_POP, POP_TOL, 3)
    else:
        assignment = START_MAP

    my_updaters       = _build_updaters()
    enacted_partition = GeographicPartition(graph=graph,
                                            assignment=assignment,
                                            updaters=my_updaters)

    scores = _functional_score_from_partition(enacted_partition)

    print(f"\n  Enacted map scores ({MODEL_MODE} mode):")
    print("  Canonical axiom-derived opportunity scores O(pi):")
    print(f"    O_B     = {scores['O_B']:.4f} expected Black opportunity districts")
    print(f"    O_L     = {scores['O_L']:.4f} expected Latino opportunity districts")
    print(f"    O_joint = {scores['O_joint']:.4f} expected coalition opportunity districts")

    print("\n  Diversity-calibrated opportunity gaps F(pi) = O(pi) - K*m_bar:")
    print(f"    F_B     = {scores['F_B']:+.4f} districts "
          f"(baseline: {scores['baseline_B']:.2f})")
    print(f"    F_L     = {scores['F_L']:+.4f} districts "
          f"(baseline: {scores['baseline_L']:.2f})")
    print(f"    F_joint = {scores['F_joint']:+.4f} districts "
          f"(baseline: {scores['baseline_joint']:.2f})")

    print(f"\n  Legacy threshold counts (cutoff = {EFFECTIVENESS_CUTOFF}):")
    print(f"    Latino-effective : {scores['hisp_eff']}")
    print(f"    Black-effective  : {scores['black_eff']}")
    print(f"    Distinct         : {scores['distinct_eff']}")

    return scores, enacted_partition


# ============================================================
# STEP 2 — Hub chain  (identical to besag_clifford_vra.py)
# ============================================================


def run_hub_chain(enacted_partition):
    """
    Run the chain forward L_HUB steps from the enacted map to reach hub X*.

    ReCom with always_accept is reversible, so running forward L steps is
    equivalent to drawing a map L steps away in state space, satisfying the
    Besag-Clifford parallel method requirement (B-C 1989, Prop 3.3).
    """
    print(f"\n=== Running hub chain ({L_HUB} steps) ===")
    t0       = time.time()
    hub_seed = stdlib_random.randint(0, 10**9)
    stdlib_random.seed(hub_seed)

    proposal, pop_constraint = _build_proposal_and_constraint(enacted_partition)
    chain = MarkovChain(
        proposal=proposal,
        constraints=[pop_constraint],
        accept=accept.always_accept,
        initial_state=enacted_partition,
        total_steps=L_HUB,
    )
    hub_partition = enacted_partition
    for step in chain:
        hub_partition = step

    hub_assignment = dict(hub_partition.assignment)
    print(f"  Hub reached in {time.time() - t0:.1f}s.")
    return hub_assignment


# ============================================================
# STEP 3 — Spoke chains
# ============================================================


def _spoke_worker(args):
    """
    Worker for a single spoke.
    args = (spoke_index, hub_assignment, seed)
    Returns one row containing O, F, and legacy threshold scores.
    """
    spoke_idx, hub_assignment, seed = args
    endpoint_assignment = _run_chain_get_endpoint(hub_assignment, L_SPOKE, seed)
    my_updaters         = _build_updaters()
    endpoint_partition  = GeographicPartition(graph=graph,
                                              assignment=endpoint_assignment,
                                              updaters=my_updaters)
    scores = _functional_score_from_partition(endpoint_partition)
    return {'spoke': spoke_idx, **scores}


def run_spokes(hub_assignment):
    """
    Spawn M_SPOKES independent chains from hub, each of length L_SPOKE.
    Returns DataFrame with one row per spoke.
    """
    print(f"\n=== Running {M_SPOKES} spokes "
          f"(L={L_SPOKE} steps each, {N_WORKERS} workers) ===")
    t0    = time.time()
    seeds = [stdlib_random.randint(0, 10**9) for _ in range(M_SPOKES)]
    args  = [(i, hub_assignment, seeds[i]) for i in range(M_SPOKES)]
    rows  = []

    if N_WORKERS > 1:
        with mp.Pool(processes=N_WORKERS) as pool:
            for i, row in enumerate(pool.imap_unordered(_spoke_worker, args)):
                rows.append(row)
                if (i + 1) % 10 == 0:
                    print(f"  {i+1}/{M_SPOKES} spokes done "
                          f"({time.time()-t0:.0f}s elapsed)")
    else:
        for i, arg in enumerate(args):
            rows.append(_spoke_worker(arg))
            if (i + 1) % 10 == 0:
                print(f"  {i+1}/{M_SPOKES} spokes done "
                      f"({time.time()-t0:.0f}s elapsed)")

    print(f"  All spokes complete in {time.time()-t0:.1f}s.")
    return pd.DataFrame(rows)


# ============================================================
# STEP 4 — Exact Besag-Clifford p-values
# ============================================================



def compute_bc_pvalues(enacted_scores, spoke_df):
    """
    Rank enacted map among spoke endpoints.

    Primary lower-tail tests use F_B, F_L, and F_joint because these
    are demographically centered versions of the axiom-derived O scores.

    O_B, O_L, and O_joint are also reported, along with ensemble-standardized
    Z scores:
        Z = (O_enacted - mean(O_spokes)) / sd(O_spokes)
    """
    M = len(spoke_df)

    def _pval(enacted_val, col):
        vals   = spoke_df[col].dropna()
        n_leq  = (vals <= enacted_val).sum()
        n_geq  = (vals >= enacted_val).sum()
        p_low  = (n_leq + 1) / (len(vals) + 1)
        p_high = (n_geq + 1) / (len(vals) + 1)
        rank   = int(n_leq) + 1
        return p_low, p_high, rank

    def _z(enacted_val, col):
        sd = spoke_df[col].std()
        if pd.isna(sd) or sd == 0:
            return float('nan')
        return float((enacted_val - spoke_df[col].mean()) / sd)

    results = {
        'mode': MODEL_MODE, 'L_hub': L_HUB, 'L_spoke': L_SPOKE,
        'M_spokes': M, 'cutoff': EFFECTIVENESS_CUTOFF,
        'm_bar_B': M_BAR_B, 'm_bar_L': M_BAR_L,
        'm_bar_combined': M_BAR_COMBINED,
        'prop_seats_B':    NUM_DISTRICTS * M_BAR_B,
        'prop_seats_L':    NUM_DISTRICTS * M_BAR_L,
        'prop_seats_comb': NUM_DISTRICTS * M_BAR_COMBINED,
    }

    for col in ['O_B', 'O_L', 'O_joint', 'F_B', 'F_L', 'F_joint']:
        results[f'enacted_{col}'] = enacted_scores[col]
        results[f'mean_{col}']    = spoke_df[col].mean()
        results[f'median_{col}']  = spoke_df[col].median()
        results[f'sd_{col}']      = spoke_df[col].std()
        results[f'p5_{col}']      = spoke_df[col].quantile(0.05)
        results[f'p95_{col}']     = spoke_df[col].quantile(0.95)

    # Ensemble-frontier standardized scores using the canonical O(pi)
    for col in ['O_B', 'O_L', 'O_joint']:
        results[f'Z_{col}'] = _z(enacted_scores[col], col)

    # Primary B-C exact p-values on calibrated F(pi)
    for label, col in [('B', 'F_B'), ('L', 'F_L'), ('joint', 'F_joint')]:
        p_low, p_high, rank = _pval(enacted_scores[col], col)
        results[f'p_{label}_lower'] = p_low
        results[f'p_{label}_upper'] = p_high
        results[f'rank_{label}'] = rank

    # Secondary p-values on canonical O(pi), useful for transparency
    for label, col in [('O_B', 'O_B'), ('O_L', 'O_L'), ('O_joint', 'O_joint')]:
        p_low, p_high, rank = _pval(enacted_scores[col], col)
        results[f'p_{label}_lower'] = p_low
        results[f'p_{label}_upper'] = p_high
        results[f'rank_{label}'] = rank

    return results


# ============================================================
# OUTPUT — Console
# ============================================================



def print_results(results, spoke_df):
    M   = results['M_spokes']
    sig = lambda p: ' *** SIGNIFICANT' if p < 0.05 else (' * marginal' if p < 0.10 else '')

    print("\n" + "=" * 72)
    print("AXIOM-DERIVED MINORITY OPPORTUNITY FUNCTIONAL")
    print("WITH DIVERSITY CALIBRATION AND BESAG-CLIFFORD EXACT TEST")
    print("=" * 72)
    print(f"Model mode           : {results['mode']}")
    print(f"Hub length (L)       : {results['L_hub']}")
    print(f"Spoke length (L)     : {results['L_spoke']}")
    print(f"Num spokes (M)       : {M}")
    print(f"Effectiveness cutoff : {results['cutoff']}  (legacy comparison only)")
    print()

    print("Canonical opportunity scores O(pi): expected opportunity districts")
    for label, col in [
        ("Black", "O_B"),
        ("Latino", "O_L"),
        ("Coalition", "O_joint"),
    ]:
        print(f"  {label}:")
        print(f"    Enacted O value      : {results[f'enacted_{col}']:.4f}")
        print(f"    Null mean +/- SD     : {results[f'mean_{col}']:.4f} +/- "
              f"{results[f'sd_{col}']:.4f}")
        print(f"    Ensemble Z score     : {results[f'Z_{col}']:+.3f}")
        print(f"    O lower-tail p-value : {results[f'p_{col}_lower']:.4f}")

    print()
    print("Primary calibrated opportunity gaps F(pi) = O(pi) - K*m_bar")
    print("Lower-tail p-values test unusually low opportunity relative to")
    print("the demographic baseline and the Besag-Clifford spoke null.")
    print()

    for label, col, pkey, rkey in [
        ("Black",     'F_B',     'p_B_lower',     'rank_B'),
        ("Latino",    'F_L',     'p_L_lower',     'rank_L'),
        ("Coalition", 'F_joint', 'p_joint_lower', 'rank_joint'),
    ]:
        print(f"  {label} calibrated functional:")
        print(f"    Enacted F value    : {results[f'enacted_{col}']:+.4f} districts")
        print(f"    Null mean +/- SD   : {results[f'mean_{col}']:+.4f} +/- "
              f"{results[f'sd_{col}']:.4f}")
        print(f"    5th--95th pct.     : [{results[f'p5_{col}']:+.3f}, "
              f"{results[f'p95_{col}']:+.3f}]")
        print(f"    Rank (of {M+1})    : {results[rkey]}")
        print(f"    p-value (lower <-) : {results[pkey]:.4f}{sig(results[pkey])}")
        print()

    print("Interpretation:")
    print("  O(pi) is the axiom-derived expected number of opportunity districts.")
    print("  F(pi) is the legally interpretable, diversity-calibrated gap.")
    print("  Z compares the enacted plan to the state-specific opportunity frontier.")
    print("  Small lower-tail B-C p-values indicate unusually low minority opportunity.")
    print("=" * 72)


# ============================================================
# OUTPUT — Distribution Plots
# ============================================================



def save_distribution_plots(enacted_scores, spoke_df, run_name):
    """
    Save two figures:
      1. Canonical O(pi) null distributions.
      2. Calibrated F(pi) null distributions.

    The F(pi) figure is the primary testing figure.
    """
    def _plot(title, base_suffix, formulas):
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))
        fig.suptitle(title, fontsize=12, fontweight='bold')

        for ax, (col, label, formula) in zip(axes, formulas):
            vals = spoke_df[col].dropna()
            enacted_val = enacted_scores[col]

            ax.hist(vals, bins=30, alpha=0.65,
                    edgecolor='white', linewidth=0.5,
                    label='Spoke null distribution')
            ax.axvline(enacted_val, linewidth=2.0, linestyle='-',
                       label=f'Enacted ({enacted_val:+.3f})')

            if col.startswith('F_'):
                ax.axvline(0, color='black', linewidth=1.2, linestyle='--',
                           label='Demographic baseline (F=0)')

            n_leq = (vals <= enacted_val).sum()
            p_val = (n_leq + 1) / (len(vals) + 1)
            ax.text(0.03, 0.97, f'p = {p_val:.4f}',
                    transform=ax.transAxes, va='top', ha='left',
                    fontsize=10, fontweight='bold')

            ax.set_xlabel('Score value (districts)', fontsize=10)
            ax.set_ylabel('Count' if ax is axes[0] else '', fontsize=10)
            ax.set_title(f'{label}\n{formula}', fontsize=9)
            ax.legend(fontsize=7, loc='upper right')
            ax.spines['top'].set_visible(False)
            ax.spines['right'].set_visible(False)

        plt.tight_layout()
        base = DIR + f'outputs/{base_suffix}_{run_name}'
        plt.savefig(base + '.pdf', bbox_inches='tight', dpi=300)
        plt.savefig(base + '.png', bbox_inches='tight', dpi=150)
        plt.close()
        print(f"Distribution plots saved:")
        print(f"  {base}.pdf")
        print(f"  {base}.png")
        return base + '.pdf'

    o_pdf = _plot(
        'Besag-Clifford Null Distribution -- Canonical Opportunity Scores O(pi)',
        'bc_canonical_O_distributions',
        [
            ('O_B',     'Black',     r'$O_B(\pi)=\sum_d p_d^B$'),
            ('O_L',     'Latino',    r'$O_L(\pi)=\sum_d p_d^L$'),
            ('O_joint', 'Coalition', r'$O_{\rm joint}(\pi)=\sum_d \max(p_d^B,p_d^L)$'),
        ]
    )

    f_pdf = _plot(
        'Besag-Clifford Null Distribution -- Calibrated Opportunity Gaps F(pi)',
        'bc_calibrated_F_distributions',
        [
            ('F_B',     'Black',     r'$F_B(\pi)=O_B(\pi)-K\bar{m}_B$'),
            ('F_L',     'Latino',    r'$F_L(\pi)=O_L(\pi)-K\bar{m}_L$'),
            ('F_joint', 'Coalition', r'$F_{\rm joint}(\pi)=O_{\rm joint}(\pi)-K\bar{m}_{\rm comb}$'),
        ]
    )

    return o_pdf, f_pdf


# ============================================================
# OUTPUT — LaTeX Table
# ============================================================


def save_latex_table(results, run_name):
    """
    Write a publication-ready LaTeX table.

    Include in paper with:
        \\input{outputs/bc_functional_table_<run_name>.tex}

    Requires: \\usepackage{booktabs}
    """
    def stars(p):
        if p < 0.01: return r'$^{***}$'
        if p < 0.05: return r'$^{**}$'
        if p < 0.10: return r'$^{*}$'
        return ''

    M  = results['M_spokes']
    pB = results['p_B_lower']
    pL = results['p_L_lower']
    pJ = results['p_joint_lower']

    lines = [
        r'% Auto-generated by besag_clifford_vra_functional.py',
        r'% Requires: \usepackage{booktabs}',
        r'\begin{table}[htbp]',
        r'\centering',
        (r'\caption{Diversity-Calibrated Minority Opportunity Functional: '
         r'Besag-Clifford Exact Significance Test (Texas HB4). '
         r'$F_g(\pi)=\sum_d p_d^g(\pi)-K\bar{m}_g$ measures the gap between '
         r'realized minority electoral opportunity and the De~Grandy proportional '
         r'baseline. $p_d^g(\pi)$ is the logit-model probability that group $g$\textquoteright s '
         r'preferred candidate wins district $d$ under plan $\pi$, estimated using '
         r'statewide ecological inference weights and recency-discounted election history. '
         r'$p$-values are exactly valid by \citet{besagclifford1989}, Proposition~3.3, '
         r'regardless of ReCom mixing time.}'),
        r'\label{tab:bc_functional}',
        r'\begin{tabular}{lccc}',
        r'\toprule',
        (r'& \textbf{Black} $F_B$ '
         r'& \textbf{Latino} $F_L$ '
         r'& \textbf{Coalition} $F_{\rm joint}$ \\'),
        r'\midrule',
        r'\multicolumn{4}{l}{\textit{Statewide proportional baseline}} \\',
        (f"Statewide CVAP fraction $\\bar{{m}}_g$ "
         f"& {results['m_bar_B']:.4f} "
         f"& {results['m_bar_L']:.4f} "
         f"& {results['m_bar_combined']:.4f} \\\\"),
        (f"Proportional seat target $K\\bar{{m}}_g$ "
         f"& {results['prop_seats_B']:.2f} "
         f"& {results['prop_seats_L']:.2f} "
         f"& {results['prop_seats_comb']:.2f} \\\\"),
        r'\midrule',
        r'\multicolumn{4}{l}{\textit{Enacted map}} \\',
        (f"$F_g(\\pi_{{\\rm enacted}})$ "
         f"& {results['enacted_F_B']:+.4f} "
         f"& {results['enacted_F_L']:+.4f} "
         f"& {results['enacted_F_joint']:+.4f} \\\\"),
        r'\midrule',
        (r'\multicolumn{4}{l}{\textit{Null distribution '
         r'($M=' + str(M) + r'$ spokes, $L=' + str(L_SPOKE) + r'$ steps each)}} \\'),
        (f"Mean $\\bar{{F}}_g$ "
         f"& {results['mean_F_B']:+.4f} "
         f"& {results['mean_F_L']:+.4f} "
         f"& {results['mean_F_joint']:+.4f} \\\\"),
        (f"Std.\\ dev.\\ "
         f"& {results['sd_F_B']:.4f} "
         f"& {results['sd_F_L']:.4f} "
         f"& {results['sd_F_joint']:.4f} \\\\"),
        (f"5th--95th pct.\\ "
         f"& [{results['p5_F_B']:+.3f}, {results['p95_F_B']:+.3f}] "
         f"& [{results['p5_F_L']:+.3f}, {results['p95_F_L']:+.3f}] "
         f"& [{results['p5_F_joint']:+.3f}, {results['p95_F_joint']:+.3f}] \\\\"),
        (f"Rank of enacted (of $M+1={M+1}$) "
         f"& {results['rank_B']} "
         f"& {results['rank_L']} "
         f"& {results['rank_joint']} \\\\"),
        r'\midrule',
        r'\multicolumn{4}{l}{\textit{Besag-Clifford exact $p$-values}} \\',
        (f"Lower-tail $p$ (dilution direction) "
         f"& {pB:.4f}{stars(pB)} "
         f"& {pL:.4f}{stars(pL)} "
         f"& {pJ:.4f}{stars(pJ)} \\\\"),
        (f"Upper-tail $p$ "
         f"& {results['p_B_upper']:.4f} "
         f"& {results['p_L_upper']:.4f} "
         f"& {results['p_joint_upper']:.4f} \\\\"),
        r'\bottomrule',
        r'\multicolumn{4}{p{0.95\linewidth}}{\footnotesize',
        r'\textit{Notes:} Lower-tail $p$-values test whether the enacted map provides',
        r'unusually \emph{few} minority opportunity seats relative to the null distribution',
        r'of randomly drawn alternative plans (the vote dilution direction).',
        r'$p$-values are exactly valid regardless of Markov chain mixing time',
        r'\citep{besagclifford1989}.',
        r'Significance: $^{*}p<0.10$, $^{**}p<0.05$, $^{***}p<0.01$ (lower-tail, one-sided).',
        f'Model mode: {results["mode"]}. Hub length $L_{{\\rm hub}}={L_HUB}$.',
        r'The proportional baseline $K\bar{m}_g$ is the De~Grandy relevant fact',
        r'\citep[512 U.S.\ 997]{degrandy1994}: proportionality is not dispositive but',
        r'is evidence in the totality of circumstances.',
        r'$F_{\rm joint}$ addresses the Section~2 coalition-claim circuit split by',
        r'crediting each district to whichever group has the higher win probability.',
        r'} \\',
        r'\end{tabular}',
        r'\end{table}',
    ]

    path = DIR + f'outputs/bc_functional_table_{run_name}.tex'
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"LaTeX table saved: {path}")
    return path


# ============================================================
# MAIN
# ============================================================


def main():
    total_start = time.time()
    master_seed = stdlib_random.randint(0, 10**9)
    stdlib_random.seed(master_seed)
    print(f"Master seed: {master_seed}")

    # 1. Score enacted map
    enacted_scores, enacted_partition = score_enacted_map()

    # 2. Hub chain
    hub_assignment = run_hub_chain(enacted_partition)

    # 3. Spoke chains
    spoke_df = run_spokes(hub_assignment)

    # 4. B-C p-values and ensemble-standardized Z scores
    results = compute_bc_pvalues(enacted_scores, spoke_df)

    # 5. Console output
    print_results(results, spoke_df)

    # 6. CSVs
    spoke_path = DIR + f'outputs/bc_opportunity_spokes_{RUN_NAME}.csv'
    pval_path  = DIR + f'outputs/bc_opportunity_results_{RUN_NAME}.csv'
    spoke_df.to_csv(spoke_path, index=False)
    pd.DataFrame([results]).to_csv(pval_path, index=False)
    print(f"\nSpoke scores saved : {spoke_path}")
    print(f"Results saved      : {pval_path}")

    # 7. Distribution plots (PDF + PNG)
    save_distribution_plots(enacted_scores, spoke_df, RUN_NAME)

    # 8. LaTeX table
    save_latex_table(results, RUN_NAME)

    print(f"\nTotal elapsed: {(time.time()-total_start)/60:.1f} minutes")
    print(f"(L_hub={L_HUB}, L_spoke={L_SPOKE}, M_spokes={M_SPOKES}, "
          f"workers={N_WORKERS})")


if __name__ == "__main__":
    main()
